using System.Globalization;
using System.IO;
using System.Media;
using System.Text.Json;

namespace EquationSynth;

public enum ValueStatus { Valid, Invalid, NaN, Infinity }
public readonly record struct EvaluationResult(double Value, ValueStatus Status) {
    public static EvaluationResult From(double value) => double.IsNaN(value) ? new(value, ValueStatus.NaN) : double.IsInfinity(value) ? new(value, ValueStatus.Infinity) : new(value, ValueStatus.Valid);
}

public sealed class ParseException(string message) : Exception(message);
public abstract class Expr { public abstract EvaluationResult Eval(double x, double t, IReadOnlyDictionary<string,double> p); public abstract void Variables(HashSet<string> result); }
public sealed class NumberExpr(double value) : Expr { public override EvaluationResult Eval(double x,double t,IReadOnlyDictionary<string,double> p)=>EvaluationResult.From(value); public override void Variables(HashSet<string> result){} }
public sealed class VariableExpr(string name) : Expr { public override EvaluationResult Eval(double x,double t,IReadOnlyDictionary<string,double> p)=>EvaluationResult.From(name switch { "x"=>x,"t"=>t,"pi"=>Math.PI,"e"=>Math.E,_=>p.TryGetValue(name,out var v)?v:double.NaN}); public override void Variables(HashSet<string> result){if(name is not("x" or "t" or "pi" or "e")) result.Add(name);} }
public sealed class UnaryExpr(char op, Expr inner) : Expr { public override EvaluationResult Eval(double x,double t,IReadOnlyDictionary<string,double> p){var a=inner.Eval(x,t,p); return a.Status==ValueStatus.Valid?EvaluationResult.From(op=='-'?-a.Value:a.Value):a;} public override void Variables(HashSet<string> result)=>inner.Variables(result); }
public sealed class BinaryExpr(char op, Expr left, Expr right) : Expr { public override EvaluationResult Eval(double x,double t,IReadOnlyDictionary<string,double> p){var a=left.Eval(x,t,p);var b=right.Eval(x,t,p);if(a.Status!=ValueStatus.Valid||b.Status!=ValueStatus.Valid)return new(double.NaN,ValueStatus.Invalid);return EvaluationResult.From(op switch{'+' => a.Value+b.Value,'-' => a.Value-b.Value,'*'=>a.Value*b.Value,'/'=>b.Value==0?double.NaN:a.Value/b.Value,'^'=>Math.Pow(a.Value,b.Value),_=>double.NaN});} public override void Variables(HashSet<string> result){left.Variables(result);right.Variables(result);} }
public sealed class FunctionExpr(string name, IReadOnlyList<Expr> args) : Expr { public override EvaluationResult Eval(double x,double t,IReadOnlyDictionary<string,double> p){var v=args.Select(a=>a.Eval(x,t,p)).ToArray();if(v.Any(a=>a.Status!=ValueStatus.Valid))return new(double.NaN,ValueStatus.Invalid);if((name is "min" or "max" or "pow") ? v.Length!=2 : v.Length!=1)return new(double.NaN,ValueStatus.Invalid);var z=name switch{"sin"=>Math.Sin(v[0].Value),"cos"=>Math.Cos(v[0].Value),"tan"=>Math.Tan(v[0].Value),"abs"=>Math.Abs(v[0].Value),"sqrt"=>Math.Sqrt(v[0].Value),"pow"=>Math.Pow(v[0].Value,v[1].Value),"log"=>Math.Log(v[0].Value),"exp"=>Math.Exp(v[0].Value),"floor"=>Math.Floor(v[0].Value),"ceil"=>Math.Ceiling(v[0].Value),"min"=>Math.Min(v[0].Value,v[1].Value),"max"=>Math.Max(v[0].Value,v[1].Value),_=>double.NaN};return EvaluationResult.From(z);} public override void Variables(HashSet<string> result){foreach(var a in args)a.Variables(result);} }

public sealed class Expression { public string Source {get;} public Expr Root {get;} public IReadOnlyList<string> Parameters {get;} private Expression(string source,Expr root,IReadOnlyList<string> parameters){Source=source;Root=root;Parameters=parameters;} public static Expression Parse(string source){var p=new Parser(source);var root=p.Parse();var set=new HashSet<string>(StringComparer.OrdinalIgnoreCase);root.Variables(set);return new(source,root,set.OrderBy(x=>x,StringComparer.OrdinalIgnoreCase).ToArray());} public EvaluationResult Evaluate(double x,double t,IReadOnlyDictionary<string,double> parameters)=>Root.Eval(x,t,parameters);}

internal sealed class Parser { readonly string s; int i; static readonly HashSet<string> Functions=new(StringComparer.OrdinalIgnoreCase){"sin","cos","tan","abs","sqrt","pow","log","exp","floor","ceil","min","max"}; public Parser(string source)=>s=source; public Expr Parse(){var e=Add();Skip();if(i<s.Length)throw Error("Unexpected token '"+s[i]+"'");return e;} ParseException Error(string m)=>new($"{m} at position {i}"); void Skip(){while(i<s.Length&&char.IsWhiteSpace(s[i]))i++;} bool Take(char c){Skip();if(i<s.Length&&s[i]==c){i++;return true;}return false;} Expr Add(){var e=Multiply();while(true){if(Take('+'))e=new BinaryExpr('+',e,Multiply());else if(Take('-'))e=new BinaryExpr('-',e,Multiply());else return e;}} Expr Multiply(){var e=Power();while(true){if(Take('*'))e=new BinaryExpr('*',e,Power());else if(Take('/'))e=new BinaryExpr('/',e,Power());else return e;}} Expr Power(){var e=Unary();if(Take('^'))e=new BinaryExpr('^',e,Power());return e;} Expr Unary(){if(Take('+'))return Unary();if(Take('-'))return new UnaryExpr('-',Unary());return Primary();} Expr Primary(){Skip();if(i>=s.Length)throw Error("Expected expression");if(Take('(')){var e=Add();if(!Take(')'))throw Error("Expected ')' ");return e;}if(char.IsDigit(s[i])||s[i]=='.'){var start=i;while(i<s.Length&&(char.IsDigit(s[i])||s[i]=='.'||s[i]=='e'||s[i]=='E'||s[i]=='+'&&i>start&&(s[i-1]=='e'||s[i-1]=='E')||s[i]=='-'&&i>start&&(s[i-1]=='e'||s[i-1]=='E')))i++;if(!double.TryParse(s[start..i],NumberStyles.Float,CultureInfo.InvariantCulture,out var n))throw Error("Invalid number");return new NumberExpr(n);}if(char.IsLetter(s[i])||s[i]=='_'){var start=i++;while(i<s.Length&&(char.IsLetterOrDigit(s[i])||s[i]=='_'))i++;var name=s[start..i].ToLowerInvariant();if(Take('(')){if(!Functions.Contains(name))throw Error($"Unknown function '{name}'");var args=new List<Expr>();if(!Take(')')){do{args.Add(Add());}while(Take(','));if(!Take(')'))throw Error("Expected ')' ");}if((name is "pow" or "min" or "max")&&args.Count!=2)throw Error($"Function {name} requires 2 arguments");if(name is not("pow" or "min" or "max")&&args.Count!=1)throw Error($"Function {name} requires 1 argument");return new FunctionExpr(name,args);}return new VariableExpr(name);}throw Error($"Unexpected token '{s[i]}'");} }

public sealed class Parameter(string name) { public string Name {get;}=name; public double Value {get;set;}=1; public double Minimum {get;set;}=-10; public double Maximum {get;set;}=10; public double Step {get;set;}=0.01; public double DefaultValue {get;set;}=1; public bool IsMetadataValid=>double.IsFinite(Minimum)&&double.IsFinite(Maximum)&&Minimum<Maximum&&double.IsFinite(Step)&&Step>0; public void Normalize(){if(!IsMetadataValid){Minimum=-10;Maximum=10;Step=.01;}Value=Math.Clamp(Value,Minimum,Maximum);} }
public sealed class ParameterSet { public List<Parameter> Items {get;}=[]; public void Sync(IEnumerable<string> names){var old=Items.ToDictionary(x=>x.Name,StringComparer.OrdinalIgnoreCase);Items.Clear();foreach(var n in names){if(old.TryGetValue(n,out var p))Items.Add(p);else Items.Add(new Parameter(n));}} public Dictionary<string,double> Values=>Items.ToDictionary(x=>x.Name,x=>x.Value,StringComparer.OrdinalIgnoreCase); }
public sealed class TimeEngine { public double Time {get;private set;} public double TimeScale {get;set;}=1; public bool IsPlaying {get;private set;} public void Play()=>IsPlaying=true;public void Pause()=>IsPlaying=false;public void Reset(){Time=0;} public void Update(double dt){if(IsPlaying)Time+=dt*TimeScale;} }
public sealed class WaveformEngine { public const int SampleCount=2048; public double[] Generate(Expression e,double t,IReadOnlyDictionary<string,double> p){var a=new double[SampleCount];for(var i=0;i<a.Length;i++){var r=e.Evaluate(i/(double)a.Length*Math.Tau,t,p);a[i]=r.Status==ValueStatus.Valid&&double.IsFinite(r.Value)?r.Value:0;}var peak=a.Max(x=>Math.Abs(x));if(peak>0)for(var i=0;i<a.Length;i++)a[i]=Math.Tanh(a[i]/peak*1.4)/Math.Tanh(1.4);return a;} }
public sealed class AudioEngine : IDisposable { SoundPlayer? player; string? file; public double Frequency {get;set;}=440;public double Volume {get;set;}=.18; public bool IsPlaying {get;private set;} public void Play(double[] table){Stop();file=Path.Combine(Path.GetTempPath(),"equation-synth.wav");WriteWave(file,table,Frequency,Volume);player=new SoundPlayer(file);player.PlayLooping();IsPlaying=true;}public void Stop(){player?.Stop();player?.Dispose();player=null;IsPlaying=false;} static void WriteWave(string path,double[] t,double freq,double volume){const int rate=44100;var frames=Math.Max(rate/(int)Math.Clamp(freq,20,2000),1);using var b=new BinaryWriter(File.Create(path));b.Write(System.Text.Encoding.ASCII.GetBytes("RIFF"));b.Write(36+frames*2);b.Write(System.Text.Encoding.ASCII.GetBytes("WAVEfmt "));b.Write(16);b.Write((short)1);b.Write((short)1);b.Write(rate);b.Write(rate*2);b.Write((short)2);b.Write((short)16);b.Write(System.Text.Encoding.ASCII.GetBytes("data"));b.Write(frames*2);for(var i=0;i<frames;i++){var pos=i*t.Length/(double)frames;var n=(int)pos;var f=pos-n;var v=t[n%t.Length]*(1-f)+t[(n+1)%t.Length]*f;v=Math.Clamp(v*volume,-1,1);b.Write((short)(v*short.MaxValue));}} public void Dispose(){Stop();if(file is not null)try{File.Delete(file);}catch{}} }

public sealed class PresetState { public string Equation {get;set;}="sin(x)"; public List<EquationData> EquationEntries {get;set;}=[]; public Guid? SelectedEquationId {get;set;} public Dictionary<string,ParameterData> Parameters {get;set;}=[]; public double Frequency {get;set;}=440;public double Volume {get;set;}=.18;public double TimeSpeed {get;set;}=1;public double XMin {get;set;}=-10;public double XMax {get;set;}=10;public double YMin {get;set;}=-5;public double YMax {get;set;}=5; } public sealed class EquationData {public Guid Id {get;set;}=Guid.NewGuid();public string ExpressionText {get;set;}="sin(x)";public string ColorHex {get;set;}="#69DAFF";public bool IsVisible {get;set;}=true;} public sealed class ParameterData {public double Value {get;set;}=1;public double Minimum {get;set;}=-10;public double Maximum {get;set;}=10;public double Step {get;set;}=.01;public double DefaultValue {get;set;}=1;}
public static class PresetService {public static void Save(string path,PresetState state)=>File.WriteAllText(path,JsonSerializer.Serialize(state,new JsonSerializerOptions{WriteIndented=true}));public static PresetState Load(string path)=>JsonSerializer.Deserialize<PresetState>(File.ReadAllText(path))??new();}
