using System.Globalization;
using System.IO;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Shapes;
using System.Windows.Threading;
using Microsoft.Win32;

namespace EquationSynth;

public partial class MainWindow : Window {
    readonly EquationDocument document = EquationDocument.CreateDefault();
    readonly GraphCamera camera = new(); readonly TimeEngine time = new(); readonly WaveformEngine waves = new();
    readonly AutomationEngine automation = new(); readonly TrailManager trails = new(); readonly AudioEngine audio = new(); readonly StereoMixerAudioEngine mixerAudio = new();
    readonly ProjectHistory<string> history = new(150); string savedState = ""; string? projectPath; bool loaded; bool restoring; bool dragging; bool timelineDragging; Point dragStart; double dragX, dragY; (double X,double Y) mouseWorld;
    readonly Dictionary<string, bool> expanded = new(StringComparer.OrdinalIgnoreCase); readonly ProceduralScene procedural = new(); readonly MixerEngine mixer = new(); readonly Dictionary<Guid,double[]> layerTables = new(); readonly DispatcherTimer animationTimer = new() { Interval = TimeSpan.FromMilliseconds(16) }; Canvas? proceduralCanvas; TextBlock? proceduralOutput;
    readonly Dictionary<Parameter, Slider> parameterSliders = new();
    public MainWindow() { InitializeComponent(); PresetBox.ItemsSource = new[] { "Sine", "Cosine", "Tangent", "Parametric", "ORBIT", "PULSE", "SPIN", "ORBIT + SPIN" }; foreach(var slider in new[]{SpeedSlider,FrequencySlider,VolumeSlider}) { slider.PreviewMouseDown += AuthorSlider_MouseDown; slider.PreviewMouseUp += AuthorSlider_MouseUp; } animationTimer.Tick += (_, _) => { time.Update(1.0/60); var result=automation.Evaluate(time.Time,document.Parameters.Items); if(result.Error is not null) { StatusText.Text="ERROR: "+result.Error; StatusText.Foreground=Brushes.Salmon; } foreach(var p in document.Parameters.Items) if(result.Values.TryGetValue(p.Name,out var value)) p.EffectiveValue=value; Refresh(false); }; Loaded += (_, _) => { loaded = true; Refresh(true); savedState = Snapshot(); animationTimer.Start(); }; }
    EquationEntry Selected => document.Selected ?? document.Equations[0];
    static SolidColorBrush Brush(string hex) => new((Color)ColorConverter.ConvertFromString(hex));
    static bool TryNumber(string text, out double value) => double.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out value) && double.IsFinite(value);
    PresetState State() => new() { Equation = Selected.ExpressionText, EquationEntries = document.Equations.Select(e => new EquationData { Id=e.Id, ExpressionText=e.ExpressionText, ColorHex=e.ColorHex, IsVisible=e.IsVisible, IsAudioEnabled=e.IsAudioEnabled, IsMuted=e.IsMuted, IsSolo=e.IsSolo, AudioFrequency=e.AudioFrequency, AudioVolume=e.AudioVolume, AudioPan=e.AudioPan, Envelope=e.Envelope }).ToList(), SelectedEquationId=document.SelectedEquationId, Procedural=procedural, Parameters=document.Parameters.Items.ToDictionary(p=>p.Name,p=>new ParameterData { Value=p.ManualValue, Minimum=p.Minimum, Maximum=p.Maximum, Step=p.Step, DefaultValue=p.DefaultValue, AutomationMode=p.Automation.Mode, Center=p.Automation.Center, Amplitude=p.Automation.Amplitude, Frequency=p.Automation.Frequency, Phase=p.Automation.Phase, AutomationExpression=p.Automation.ExpressionText }), Frequency=FrequencySlider.Value, Volume=VolumeSlider.Value, Muted=MuteCheck.IsChecked==true, MasterVolume=mixer.MasterGain, TimeSpeed=SpeedSlider.Value, TimelineStart=TimelineSlider.Minimum, TimelineEnd=TimelineSlider.Maximum, CurrentTime=time.Time, LoopStart=time.LoopStart, LoopEnd=time.LoopEnd, LoopEnabled=LoopCheck.IsChecked==true, XMin=camera.XMin, XMax=camera.XMax, YMin=camera.YMin, YMax=camera.YMax, GridEnabled=GridCheck.IsChecked!=false, AxesEnabled=AxesCheck.IsChecked!=false, TrailsEnabled=TrailsCheck.IsChecked==true, TrailCount=(int)TrailCountSlider.Value };
    string Snapshot() => AuthoredStateCodec.Serialize(State());
    void Reconcile() { document.ReconcileParameters(procedural.Objects.SelectMany(o=>o.OutputBindings).Where(b=>b.ParsedExpression is not null).SelectMany(b=>b.ParsedExpression!.Parameters)); foreach(var p in document.Parameters.Items) p.Normalize(); }
    void Author(Action action, bool rebuild=true) { if(restoring)return; var before=Snapshot(); action(); if(rebuild)Reconcile(); var after=Snapshot(); if(!AuthoredStateCodec.Equal(before,after)){history.Record(before); MarkDirty();} Refresh(rebuild); }
    void BeginDrag() { if(!loaded||restoring)return; _dragBefore ??= Snapshot(); }
    string? _dragBefore;
    void EndDrag() { if(_dragBefore is null)return; var after=Snapshot();if(!AuthoredStateCodec.Equal(_dragBefore,after)){history.Record(_dragBefore);MarkDirty();} _dragBefore=null; }
    void MarkDirty() { DirtyText.Text="* UNSAVED"; Title="Equation Synth *"; }
    void RecomputeDirty() { var dirty=!AuthoredStateCodec.Equal(savedState,Snapshot());DirtyText.Text=dirty?"* UNSAVED":"";Title=dirty?"Equation Synth *":"Equation Synth";StatusBarText.Text=$"{document.Equations.Count} equation{(document.Equations.Count==1?"":"s")} | {document.Parameters.Items.Count} parameter{(document.Parameters.Items.Count==1?"":"s")} | t={time.Time:0.000} | Audio: {(mixerAudio.IsPlaying?mixerAudio.Status:audio.Status)}"; }
    void Refresh(bool rebuildUi) { if(rebuildUi){BuildEquationList();BuildProceduralPanel();BuildParameters();UpdateLayerTables();} TimeText.Text=$"t = {time.Time:0.000}";SpeedText.Text=$"{SpeedSlider.Value:0.0}x";FrequencyText.Text=$"{FrequencySlider.Value:0} Hz";VolumeText.Text=$"{VolumeSlider.Value:0.00}";AudioStatusText.Text=$"{(mixerAudio.IsPlaying?mixerAudio.Status:audio.Status)} · {AudioEngine.SampleRate} Hz · {WaveformEngine.SampleCount} samples"; DrawGraph();DrawWave();DrawProcedural();RecomputeDirty(); }
    void UpdateLayerTables(){foreach(var layer in document.Equations)if(layer.ParsedExpression is not null)layerTables[layer.Id]=waves.Generate(layer.ParsedExpression,time.Time,document.Parameters.Values);mixer.Reconcile(document.Equations,layerTables);}
    double[] MasterTable(){UpdateLayerTables();var enabled=document.Equations.Where(e=>MixerMath.IsAudible(e,document.Equations.Any(x=>x.IsSolo))).ToList();var table=new double[WaveformEngine.SampleCount];foreach(var layer in enabled)if(layerTables.TryGetValue(layer.Id,out var source))for(var i=0;i<table.Length;i++)table[i]+=source[i]*layer.AudioVolume;var scale=Math.Max(1,enabled.Count);for(var i=0;i<table.Length;i++)table[i]=Math.Tanh(table[i]/Math.Sqrt(scale)*mixer.MasterGain*1.4);return table;}
    void BuildEquationList(){EquationsPanel.Children.Clear();foreach(var e in document.Equations){var card=new StackPanel{Margin=new Thickness(2),Background=e.IsSelected?new SolidColorBrush(Color.FromRgb(35,67,82)):Brushes.Transparent};var row=new DockPanel();var eye=new CheckBox{IsChecked=e.IsVisible,Content="◉",Width=28,Tag=e};eye.Click+=(s,x)=>Author(()=>e.IsVisible=eye.IsChecked==true,false);var audioEnabled=new CheckBox{IsChecked=e.IsAudioEnabled,Content="AUDIO",Tag=e};audioEnabled.Click+=(s,x)=>Author(()=>e.IsAudioEnabled=audioEnabled.IsChecked==true,false);var mute=new CheckBox{IsChecked=e.IsMuted,Content="MUTE",Tag=e};mute.Click+=(s,x)=>Author(()=>e.IsMuted=mute.IsChecked==true,false);var solo=new CheckBox{IsChecked=e.IsSolo,Content="SOLO",Tag=e};solo.Click+=(s,x)=>Author(()=>e.IsSolo=solo.IsChecked==true,false);var name=new TextBlock{Text=e.DisplayName,Foreground=Brushes.White,Margin=new Thickness(4)};var del=new Button{Content="×",Tag=e};del.Click+=(s,x)=>Author(()=>{document.Select(e);document.RemoveSelected();});row.Children.Add(eye);row.Children.Add(new Border{Width=12,Height=12,Background=Brush(e.ColorHex),Margin=new Thickness(4)});row.Children.Add(name);row.Children.Add(audioEnabled);row.Children.Add(mute);row.Children.Add(solo);row.Children.Add(del);card.Children.Add(row);var controls=new StackPanel{Orientation=Orientation.Horizontal};controls.Children.Add(new TextBlock{Text="Hz",Margin=new Thickness(2)});controls.Children.Add(LayerSlider(e,20,2000,e.AudioFrequency,(v)=>e.AudioFrequency=v));controls.Children.Add(new TextBlock{Text="Vol",Margin=new Thickness(2)});controls.Children.Add(LayerSlider(e,0,1,e.AudioVolume,(v)=>e.AudioVolume=v));controls.Children.Add(new TextBlock{Text="Pan",Margin=new Thickness(2)});controls.Children.Add(LayerSlider(e,-1,1,e.AudioPan,(v)=>e.AudioPan=v));controls.Children.Add(new TextBlock{Text="A/D/S/R",Margin=new Thickness(2)});controls.Children.Add(EnvelopeSlider(e,0,2,e.Envelope.Attack,v=>e.Envelope.Attack=v));controls.Children.Add(EnvelopeSlider(e,0,2,e.Envelope.Decay,v=>e.Envelope.Decay=v));controls.Children.Add(EnvelopeSlider(e,0,1,e.Envelope.Sustain,v=>e.Envelope.Sustain=v));controls.Children.Add(EnvelopeSlider(e,0,2,e.Envelope.Release,v=>e.Envelope.Release=v));card.Children.Add(controls);row.MouseLeftButtonDown+=(s,x)=>{document.Select(e);EquationBox.Text=e.ExpressionText;Refresh(true);};EquationsPanel.Children.Add(card);} }
    Slider LayerSlider(EquationEntry e,double min,double max,double value,Action<double> assign){var slider=new Slider{Minimum=min,Maximum=max,Value=value,Width=70,Tag=e};slider.PreviewMouseDown+=(s,x)=>BeginDrag();slider.PreviewMouseUp+=(s,x)=>EndDrag();slider.ValueChanged+=(s,x)=>{if(!restoring){assign(slider.Value);UpdateLayerTables();Refresh(false);}};return slider;}
    Slider EnvelopeSlider(EquationEntry e,double min,double max,double value,Action<double> assign){var slider=new Slider{Minimum=min,Maximum=max,Value=value,Width=42,Tag=e,ToolTip=value.ToString("0.##")};slider.PreviewMouseDown+=(s,x)=>BeginDrag();slider.PreviewMouseUp+=(s,x)=>EndDrag();slider.ValueChanged+=(s,x)=>{if(!restoring){assign(slider.Value);Refresh(false);}};return slider;}
    void BuildParameters(){ParametersPanel.Children.Clear();parameterSliders.Clear();foreach(var p in document.Parameters.Items){var panel=new StackPanel{Margin=new Thickness(0,3,0,8)};var label=new TextBlock{Foreground=Brushes.White};var slider=new Slider{Minimum=p.Minimum,Maximum=p.Maximum,Value=p.ManualValue,TickFrequency=p.Step,Tag=p};parameterSliders[p]=slider;slider.PreviewMouseDown+=(s,e)=>BeginDrag();slider.PreviewMouseUp+=(s,e)=>EndDrag();slider.ValueChanged+=(s,e)=>{if(restoring)return;p.ManualValue=slider.Value;p.EffectiveValue=p.ManualValue;label.Text=$"{p.Name}  Manual: {p.ManualValue:0.###}  Effective: {p.EffectiveValue:0.###}";UpdateLayerTables();Refresh(false);};label.Text=$"{p.Name}  Manual: {p.ManualValue:0.###}  Effective: {p.EffectiveValue:0.###}";panel.Children.Add(label);panel.Children.Add(slider);var edit=new Button{Content=expanded.ContainsKey(p.Name)&&expanded[p.Name]?"COLLAPSE":"EDIT",Tag=p};edit.Click+=(s,e)=>{expanded[p.Name]=!expanded.GetValueOrDefault(p.Name);BuildParameters();};panel.Children.Add(edit);if(expanded.GetValueOrDefault(p.Name))BuildMetadata(panel,p);ParametersPanel.Children.Add(panel);} }
    void BuildMetadata(StackPanel panel,Parameter p){panel.Children.Add(new TextBlock{Text=$"PARAMETER: {p.Name}",Foreground=Brushes.LightBlue});AddField(panel,"Manual value",p.ManualValue,x=>p.ManualValue=x);AddField(panel,"Minimum",p.Minimum,x=>p.Minimum=x);AddField(panel,"Maximum",p.Maximum,x=>p.Maximum=x);AddField(panel,"Step",p.Step,x=>p.Step=x);var mode=new ComboBox{ItemsSource=Enum.GetValues<AutomationMode>(),SelectedItem=p.Automation.Mode,Tag=p};mode.SelectionChanged+=(s,e)=>{if(mode.SelectedItem is AutomationMode m)Author(()=>{p.Automation.Mode=m;p.Automation.TryParse(out var err);if(err.Length>0)StatusText.Text="ERROR: "+err;});};panel.Children.Add(new TextBlock{Text="Automation"});panel.Children.Add(mode);var automationPanel=new StackPanel();panel.Children.Add(automationPanel);void UpdateAutomation(){automationPanel.Children.Clear();if(p.Automation.Mode is AutomationMode.Sine or AutomationMode.Cosine){AddField(automationPanel,"Center",p.Automation.Center,x=>p.Automation.Center=x);AddField(automationPanel,"Amplitude",p.Automation.Amplitude,x=>p.Automation.Amplitude=x);AddField(automationPanel,"Frequency",p.Automation.Frequency,x=>p.Automation.Frequency=x);AddField(automationPanel,"Phase",p.Automation.Phase,x=>p.Automation.Phase=x);}else if(p.Automation.Mode==AutomationMode.Expression){var box=new TextBox{Text=p.Automation.ExpressionText};box.LostFocus+=(s,e)=>Author(()=>{p.Automation.ExpressionText=box.Text;p.Automation.TryParse(out var err);StatusText.Text=err.Length==0?"VALID":"ERROR: "+err;});automationPanel.Children.Add(new TextBlock{Text="Automation Expression"});automationPanel.Children.Add(box);}}UpdateAutomation();var reset=new Button{Content="RESET VALUE"};reset.Click+=(s,e)=>Author(()=>p.ManualValue=p.DefaultValue);panel.Children.Add(reset);}
    void AddField(StackPanel panel,string name,double value,Action<double> assign){var row=new DockPanel();row.Children.Add(new TextBlock{Text=name,Width=110});var box=new TextBox{Text=value.ToString("G",CultureInfo.InvariantCulture)};box.LostFocus+=(s,e)=>{if(!TryNumber(box.Text,out var n)){StatusText.Text="ERROR: value must be finite";box.Text=value.ToString("G",CultureInfo.InvariantCulture);return;}Author(()=>{assign(n);var p=panel.Children.OfType<Slider>().FirstOrDefault();});};row.Children.Add(box);panel.Children.Add(row);}
    void Apply_Click(object s,RoutedEventArgs e)=>Apply();void EquationBox_KeyDown(object s,KeyEventArgs e){if(e.Key==Key.Enter){Apply();e.Handled=true;}}
    void Apply(){var e=Selected;var next=EquationBox.Text;try{Expression.Parse(next);}catch(ParseException ex){StatusText.Text="ERROR: "+ex.Message;StatusText.Foreground=Brushes.Salmon;return;}Author(()=>{e.ExpressionText=next;e.TryParse(out _);StatusText.Text="VALID";StatusText.Foreground=new SolidColorBrush(Color.FromRgb(116,227,155));});}
    void AddEquation_Click(object s,RoutedEventArgs e)=>Author(()=>document.Add());void Color_Click(object s,RoutedEventArgs e)=>Author(()=>Selected.ColorHex=(string)((Button)s).Tag);void MoveUp_Click(object s,RoutedEventArgs e)=>Reorder(-1);void MoveDown_Click(object s,RoutedEventArgs e)=>Reorder(1);void Reorder(int direction)=>Author(()=>{var i=document.Equations.IndexOf(Selected);var j=i+direction;if(j>=0&&j<document.Equations.Count)(document.Equations[i],document.Equations[j])=(document.Equations[j],document.Equations[i]);});
    void ViewApply_Click(object s,RoutedEventArgs e){if(TryNumber(XMinBox.Text,out var a)&&TryNumber(XMaxBox.Text,out var b)&&TryNumber(YMinBox.Text,out var c)&&TryNumber(YMaxBox.Text,out var d)&&a<b&&c<d)Author(()=>camera.Set(a,b,c,d),false);else StatusText.Text="ERROR: graph ranges are invalid";}void ResetView_Click(object s,RoutedEventArgs e)=>Author(()=>{camera.Reset();XMinBox.Text="-10";XMaxBox.Text="10";YMinBox.Text="-5";YMaxBox.Text="5";},false);void ViewToggle_Click(object s,RoutedEventArgs e)=>Author(()=>{},false);
    void Trails_Changed(object s,RoutedEventArgs e)=>Author(()=>{trails.Enabled=TrailsCheck.IsChecked==true;},false);void TrailCount_Changed(object s,RoutedPropertyChangedEventArgs<double> e){if(loaded)Author(()=>trails.Count=(int)TrailCountSlider.Value,false);}
    void AuthorSlider_MouseDown(object s,MouseButtonEventArgs e)=>BeginDrag();void AuthorSlider_MouseUp(object s,MouseButtonEventArgs e)=>EndDrag();void Setting_Changed(object s,RoutedPropertyChangedEventArgs<double> e){if(loaded&&!restoring){time.TimeScale=SpeedSlider.Value;mixer.MasterGain=VolumeSlider.Value;Refresh(false);}}void Mute_Click(object s,RoutedEventArgs e)=>Author(()=>{},false);void TimePlay_Click(object s,RoutedEventArgs e)=>time.Play();void TimePause_Click(object s,RoutedEventArgs e)=>time.Pause();void TimeReset_Click(object s,RoutedEventArgs e){time.Reset();Refresh(false);}void StepBack_Click(object s,RoutedEventArgs e){time.Step(-1.0/60);Refresh(false);}void StepForward_Click(object s,RoutedEventArgs e){time.Step(1.0/60);Refresh(false);}
    void Timeline_MouseDown(object s,MouseButtonEventArgs e){timelineDragging=true;time.Pause();BeginDrag();}void Timeline_MouseUp(object s,MouseButtonEventArgs e){timelineDragging=false;EndDrag();}void Timeline_Changed(object s,RoutedPropertyChangedEventArgs<double> e){if(timelineDragging||!time.IsPlaying)time.SetTime(TimelineSlider.Value);Refresh(false);}void Loop_Changed(object s,RoutedEventArgs e){if(restoring)return;if(TryNumber(LoopStartBox.Text,out var a)&&TryNumber(LoopEndBox.Text,out var b)&&b>a)Author(()=>{time.LoopStart=a;time.LoopEnd=b;time.LoopEnabled=LoopCheck.IsChecked==true;TimelineSlider.Minimum=a;TimelineSlider.Maximum=b;},false);}
    void Graph_MouseWheel(object s,MouseWheelEventArgs e){var at=camera.ScreenToWorld(e.GetPosition(GraphCanvas).X,e.GetPosition(GraphCanvas).Y,GraphCanvas.ActualWidth,GraphCanvas.ActualHeight);Author(()=>camera.ZoomAt(e.Delta>0?.8:1.25,at.X,at.Y),false);}void Graph_MouseDown(object s,MouseButtonEventArgs e){dragging=true;dragStart=e.GetPosition(GraphCanvas);dragX=camera.CenterX;dragY=camera.CenterY;BeginDrag();GraphCanvas.CaptureMouse();}void Graph_MouseUp(object s,MouseButtonEventArgs e){dragging=false;GraphCanvas.ReleaseMouseCapture();EndDrag();}void Graph_MouseMove(object s,MouseEventArgs e){var pos=e.GetPosition(GraphCanvas);mouseWorld=camera.ScreenToWorld(pos.X,pos.Y,GraphCanvas.ActualWidth,GraphCanvas.ActualHeight);CoordinateText.Text=$"x = {mouseWorld.X:0.000}    y = {mouseWorld.Y:0.000}";if(!dragging)return;var dx=pos.X-dragStart.X;var dy=pos.Y-dragStart.Y;camera.Set(dragX-dx/GraphCanvas.ActualWidth*camera.Width,dragX-dx/GraphCanvas.ActualWidth*camera.Width+camera.Width,dragY+dy/GraphCanvas.ActualHeight*camera.Height,dragY+dy/GraphCanvas.ActualHeight*camera.Height-camera.Height);Refresh(false);}void Canvas_SizeChanged(object s,SizeChangedEventArgs e)=>Refresh(false);
    void DrawGraph(){GraphCanvas.Children.Clear();var w=GraphCanvas.ActualWidth;var h=GraphCanvas.ActualHeight;if(w<2||h<2)return;var sx=GraphSampler.NiceSpacing(camera.Width);var sy=GraphSampler.NiceSpacing(camera.Height);if(GridCheck.IsChecked!=false){for(var x=Math.Ceiling(camera.XMin/sx)*sx;x<=camera.XMax;x+=sx){var p=camera.WorldToScreen(x,0,w,h);GraphCanvas.Children.Add(new Line{X1=p.X,X2=p.X,Y1=0,Y2=h,Stroke=new SolidColorBrush(Color.FromArgb(40,130,170,190))});}for(var y=Math.Ceiling(camera.YMin/sy)*sy;y<=camera.YMax;y+=sy){var p=camera.WorldToScreen(0,y,w,h);GraphCanvas.Children.Add(new Line{X1=0,X2=w,Y1=p.Y,Y2=p.Y,Stroke=new SolidColorBrush(Color.FromArgb(40,130,170,190))});}}if(AxesCheck.IsChecked!=false){var o=camera.WorldToScreen(0,0,w,h);GraphCanvas.Children.Add(new Line{X1=o.X,X2=o.X,Y1=0,Y2=h,Stroke=Brushes.Gray});GraphCanvas.Children.Add(new Line{X1=0,X2=w,Y1=o.Y,Y2=o.Y,Stroke=Brushes.Gray});}foreach(var e in document.Equations.Where(x=>x.IsVisible&&x.ParsedExpression is not null)){var line=new Polyline{Stroke=Brush(e.ColorHex),StrokeThickness=e.IsSelected?2.5:1.5};foreach(var q in GraphSampler.Sample(e,camera,time.Time,document.Parameters.Values,w))if(q.Valid)line.Points.Add(new Point(camera.WorldToScreen(q.X,q.Y,w,h).X,camera.WorldToScreen(q.X,q.Y,w,h).Y));if(line.Points.Count>1)GraphCanvas.Children.Add(line);}}
    void DrawWave(){WaveCanvas.Children.Clear();var w=WaveCanvas.ActualWidth;var h=WaveCanvas.ActualHeight;if(w<2||h<2)return;var table=waves.Generate(Selected.ParsedExpression!,time.Time,document.Parameters.Values);audio.Frequency=FrequencySlider.Value;audio.Volume=MuteCheck.IsChecked==true?0:VolumeSlider.Value;if(audio.IsPlaying)audio.SetWavetable(table);var p=new Polyline{Stroke=Brush(Selected.ColorHex),StrokeThickness=2};for(int i=0;i<table.Length;i++)p.Points.Add(new Point(i*w/(table.Length-1),h/2-table[i]*(h*.42)));WaveCanvas.Children.Add(p);}
    void SoundPlay_Click(object s,RoutedEventArgs e){mixer.GateOn();try{mixerAudio.Play(mixer);}catch(Exception ex){StatusText.Text="ERROR: "+ex.Message;}Refresh(false);}void SoundStop_Click(object s,RoutedEventArgs e){mixer.GateOff();mixerAudio.Stop();audio.Stop();Refresh(false);}
    bool TryResolveUnsavedChanges(){if(AuthoredStateCodec.Equal(savedState,Snapshot()))return true;var answer=MessageBox.Show("Save changes to current project?","Equation Synth",MessageBoxButton.YesNoCancel,MessageBoxImage.Warning);if(answer==MessageBoxResult.Cancel)return false;if(answer==MessageBoxResult.No)return true;return SaveProject(false);}
    bool SaveProject(bool saveAs){var path=saveAs?null:projectPath;if(path is null){var d=new SaveFileDialog{Filter="Equation project|*.equation.json"};if(d.ShowDialog()!=true)return false;path=d.FileName;}try{var state=State();var errors=ProjectValidator.Validate(ToProject(state)).Concat(ProceduralValidator.Validate(state.Procedural)).ToArray();if(errors.Length>0)throw new InvalidDataException(string.Join(Environment.NewLine,errors));File.WriteAllText(path!,JsonSerializer.Serialize(state,new JsonSerializerOptions{WriteIndented=true}));projectPath=path;savedState=Snapshot();RecomputeDirty();return true;}catch(Exception ex){MessageBox.Show("Could not save project: "+ex.Message,"Equation Synth",MessageBoxButton.OK,MessageBoxImage.Error);return false;}}
    EquationProject ToProject(PresetState state){var p=EquationProject.CreateNew();p.Document.Equations.Clear();foreach(var e in state.EquationEntries){var item=new EquationEntry{Id=e.Id,ExpressionText=e.ExpressionText,ColorHex=e.ColorHex,IsVisible=e.IsVisible,IsAudioEnabled=e.IsAudioEnabled,IsMuted=e.IsMuted,IsSolo=e.IsSolo,AudioFrequency=e.AudioFrequency,AudioVolume=e.AudioVolume,AudioPan=e.AudioPan,Envelope=e.Envelope};item.TryParse(out _);p.Document.Equations.Add(item);}if(p.Document.Equations.Count==0){var item=p.Document.Add(state.Equation);item.IsAudioEnabled=true;}p.Document.Select(p.Document.Equations.FirstOrDefault(x=>x.Id==state.SelectedEquationId)??p.Document.Equations[0]);if(p.Document.Equations.All(x=>!x.IsAudioEnabled))p.Document.Selected!.IsAudioEnabled=true;p.Document.ReconcileParameters();foreach(var q in p.Document.Parameters.Items)if(state.Parameters.TryGetValue(q.Name,out var d)){q.ManualValue=d.Value;q.Minimum=d.Minimum;q.Maximum=d.Maximum;q.Step=d.Step;q.DefaultValue=d.DefaultValue;q.Automation.Mode=d.AutomationMode;q.Automation.Center=d.Center;q.Automation.Amplitude=d.Amplitude;q.Automation.Frequency=d.Frequency;q.Automation.Phase=d.Phase;q.Automation.ExpressionText=d.AutomationExpression;q.Automation.TryParse(out _);}p.Graph.XMin=state.XMin;p.Graph.XMax=state.XMax;p.Graph.YMin=state.YMin;p.Graph.YMax=state.YMax;p.Time.TimelineStart=state.TimelineStart;p.Time.TimelineEnd=state.TimelineEnd;p.Time.TimeScale=state.TimeSpeed;p.Audio.Frequency=state.Frequency;p.Audio.Volume=state.Volume;p.Rebuild();return p;}
    void LoadPath(string path){var state=AuthoredStateCodec.Deserialize(File.ReadAllText(path));var candidate=ToProject(state);var errors=ProjectValidator.Validate(candidate).Concat(ProceduralValidator.Validate(state.Procedural)).ToArray();if(errors.Length>0)throw new InvalidDataException(string.Join(Environment.NewLine,errors));restoring=true;try{document.Equations.Clear();foreach(var e in candidate.Document.Equations)document.Equations.Add(e);document.Select(document.Equations.First());document.Select(document.Equations.FirstOrDefault(x=>x.Id==state.SelectedEquationId)??document.Equations[0]);SyncProcedural(state);Reconcile();foreach(var p in document.Parameters.Items)if(state.Parameters.TryGetValue(p.Name,out var d)){p.ManualValue=d.Value;p.Minimum=d.Minimum;p.Maximum=d.Maximum;p.Step=d.Step;p.DefaultValue=d.DefaultValue;p.Automation.Mode=d.AutomationMode;p.Automation.Center=d.Center;p.Automation.Amplitude=d.Amplitude;p.Automation.Frequency=d.Frequency;p.Automation.Phase=d.Phase;p.Automation.ExpressionText=d.AutomationExpression;p.Automation.TryParse(out _);}FrequencySlider.Value=state.Frequency;VolumeSlider.Value=state.Volume;MuteCheck.IsChecked=state.Muted;SpeedSlider.Value=state.TimeSpeed;TimelineSlider.Minimum=state.TimelineStart;TimelineSlider.Maximum=state.TimelineEnd;time.LoopStart=state.LoopStart;time.LoopEnd=state.LoopEnd;LoopCheck.IsChecked=state.LoopEnabled;time.SetTime(state.CurrentTime);camera.Set(state.XMin,state.XMax,state.YMin,state.YMax);GridCheck.IsChecked=state.GridEnabled;AxesCheck.IsChecked=state.AxesEnabled;TrailsCheck.IsChecked=state.TrailsEnabled;TrailCountSlider.Value=state.TrailCount;projectPath=path;history.Clear();}finally{restoring=false;}savedState=Snapshot();EquationBox.Text=Selected.ExpressionText;Refresh(true);}
    void NewProject_Click(object s,RoutedEventArgs e){if(!TryResolveUnsavedChanges())return;restoring=true;try{mixerAudio.Stop();audio.Stop();document.Equations.Clear();document.Add();procedural.Objects.Clear();procedural.SelectedObjectId=null;camera.Reset();time.Reset();history.Clear();projectPath=null;expanded.Clear();}finally{restoring=false;}savedState=Snapshot();EquationBox.Text=Selected.ExpressionText;Refresh(true);}
    void SaveProject_Click(object s,RoutedEventArgs e)=>SaveProject(false);void SaveAsProject_Click(object s,RoutedEventArgs e)=>SaveProject(true);void LoadProject_Click(object s,RoutedEventArgs e)=>LoadProject();void LoadProject(){if(!TryResolveUnsavedChanges())return;var d=new OpenFileDialog{Filter="Equation project|*.equation.json"};if(d.ShowDialog()!=true)return;try{LoadPath(d.FileName);}catch(Exception ex){MessageBox.Show("Could not load project: "+ex.Message,"Equation Synth",MessageBoxButton.OK,MessageBoxImage.Error);}}
    void Save_Click(object s,RoutedEventArgs e)=>SaveProject(true);void Load_Click(object s,RoutedEventArgs e)=>LoadProject();void Preset_Changed(object s,SelectionChangedEventArgs e){if(PresetBox.SelectedItem is not string n)return;if(n is "ORBIT" or "PULSE" or "SPIN" or "ORBIT + SPIN"){Author(()=>{var o=procedural.Add(n);if(n is "ORBIT" or "ORBIT + SPIN"){o.OutputBindings.Add(new ExpressionOutputBinding{Name="X",Target=OutputTarget.PositionX,Mode=OutputCombineMode.Add,ExpressionText="150*cos(t)"});o.OutputBindings.Add(new ExpressionOutputBinding{Name="Y",Target=OutputTarget.PositionY,Mode=OutputCombineMode.Add,ExpressionText="150*sin(t)"});}if(n is "SPIN" or "ORBIT + SPIN")o.OutputBindings.Add(new ExpressionOutputBinding{Name="Rotation",Target=OutputTarget.Rotation,Mode=OutputCombineMode.Add,ExpressionText="90*t"});if(n=="PULSE")o.OutputBindings.Add(new ExpressionOutputBinding{Name="Scale",Target=OutputTarget.Scale,Mode=OutputCombineMode.Add,ExpressionText="0.25*sin(t*2)"});foreach(var b in o.OutputBindings)b.TryParse(out _);});return;}var text=n switch{"Sine"=>"sin(x)","Cosine"=>"cos(x)","Tangent"=>"tan(x)",_=>"sin(x*a)"};Author(()=>{Selected.ExpressionText=text;Selected.TryParse(out _);EquationBox.Text=text;});}
    void Undo(){var state=history.Undo(Snapshot());if(state is null)return;RestoreSnapshot(state);}void Redo(){var state=history.Redo(Snapshot());if(state is null)return;RestoreSnapshot(state);}void RestoreSnapshot(string text){var state=AuthoredStateCodec.Deserialize(text);restoring=true;try{LoadState(state);}finally{restoring=false;}Refresh(true);}
    void LoadState(PresetState state){var candidate=ToProject(state);document.Equations.Clear();foreach(var e in candidate.Document.Equations)document.Equations.Add(e);document.Select(document.Equations.FirstOrDefault(e=>e.Id==state.SelectedEquationId)??document.Equations[0]);document.ReconcileParameters();foreach(var p in document.Parameters.Items)if(state.Parameters.TryGetValue(p.Name,out var d)){p.ManualValue=d.Value;p.Minimum=d.Minimum;p.Maximum=d.Maximum;p.Step=d.Step;p.DefaultValue=d.DefaultValue;p.Automation.Mode=d.AutomationMode;p.Automation.Center=d.Center;p.Automation.Amplitude=d.Amplitude;p.Automation.Frequency=d.Frequency;p.Automation.Phase=d.Phase;p.Automation.ExpressionText=d.AutomationExpression;p.Automation.TryParse(out _);}SyncProcedural(state);FrequencySlider.Value=state.Frequency;VolumeSlider.Value=state.Volume;mixer.MasterGain=state.MasterVolume;MuteCheck.IsChecked=state.Muted;SpeedSlider.Value=state.TimeSpeed;TimelineSlider.Minimum=state.TimelineStart;TimelineSlider.Maximum=state.TimelineEnd;time.LoopStart=state.LoopStart;time.LoopEnd=state.LoopEnd;time.LoopEnabled=state.LoopEnabled;time.SetTime(state.CurrentTime);camera.Set(state.XMin,state.XMax,state.YMin,state.YMax);GridCheck.IsChecked=state.GridEnabled;AxesCheck.IsChecked=state.AxesEnabled;TrailsCheck.IsChecked=state.TrailsEnabled;TrailCountSlider.Value=state.TrailCount;EquationBox.Text=Selected.ExpressionText;}
    void Window_Closing(object? s,System.ComponentModel.CancelEventArgs e){if(!TryResolveUnsavedChanges()){e.Cancel=true;return;}animationTimer.Stop();mixerAudio.Stop();audio.Stop();}
    void Window_KeyDown(object s,KeyEventArgs e){bool text=Keyboard.FocusedElement is TextBox;var mod=Keyboard.Modifiers;if(mod==ModifierKeys.Control&&e.Key==Key.Z&&!text){Undo();e.Handled=true;}else if((mod==ModifierKeys.Control&&e.Key==Key.Y)||(mod==(ModifierKeys.Control|ModifierKeys.Shift)&&e.Key==Key.Z)){if(!text)Redo();e.Handled=true;}else if(mod==ModifierKeys.Control&&e.Key==Key.N&&!text){NewProject_Click(s,new RoutedEventArgs());e.Handled=true;}else if(mod==ModifierKeys.Control&&e.Key==Key.O&&!text){LoadProject();e.Handled=true;}else if(mod==ModifierKeys.Control&&e.Key==Key.S&&!text){SaveProject(false);e.Handled=true;}else if(mod==(ModifierKeys.Control|ModifierKeys.Shift)&&e.Key==Key.S&&!text){SaveProject(true);e.Handled=true;}else if(mod==ModifierKeys.Control&&e.Key==Key.D&&!text){Author(()=>{var source=Selected;var copy=document.Add(source.ExpressionText);copy.ColorHex=EquationDocument.Palette[(document.Equations.Count-1)%EquationDocument.Palette.Length];copy.AudioFrequency=source.AudioFrequency;copy.AudioVolume=source.AudioVolume;copy.AudioPan=source.AudioPan;copy.Envelope=new EnvelopeSettings{Attack=source.Envelope.Attack,Decay=source.Envelope.Decay,Sustain=source.Envelope.Sustain,Release=source.Envelope.Release};});e.Handled=true;}else if(e.Key==Key.Delete&&!text){Author(()=>document.RemoveSelected());e.Handled=true;}else if(e.Key==Key.Space&&!text){if(time.IsPlaying)time.Pause();else time.Play();e.Handled=true;}else if(e.Key==Key.Escape){mixerAudio.Stop();audio.Stop();e.Handled=true;}else if(e.Key==Key.R&&!text){ResetView_Click(s,new RoutedEventArgs());e.Handled=true;}else if(e.Key==Key.F&&!text){AutoFitY();e.Handled=true;}}
    void AutoFitY(){var values=document.Equations.Where(e=>e.IsVisible).SelectMany(e=>GraphSampler.Sample(e,camera,time.Time,document.Parameters.Values,GraphCanvas.ActualWidth)).Where(p=>p.Valid).Select(p=>p.Y).ToList();if(values.Count<2)return;var pad=Math.Max((values.Max()-values.Min())*.15,.5);Author(()=>{camera.Set(camera.XMin,camera.XMax,values.Min()-pad,values.Max()+pad);YMinBox.Text=camera.YMin.ToString("0.###");YMaxBox.Text=camera.YMax.ToString("0.###");},false);}
}
