using System.Globalization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Shapes;

namespace EquationSynth;

public partial class MainWindow {
    void SyncProcedural(PresetState state){procedural.Objects=state.Procedural?.Objects??[];procedural.SelectedObjectId=state.Procedural?.SelectedObjectId;foreach(var o in procedural.Objects)foreach(var b in o.OutputBindings)b.TryParse(out _);}
    void BuildProceduralPanel(){var box=new GroupBox{Header="PROCEDURAL OUTPUTS",Margin=new Thickness(0,4,0,4)};var panel=new StackPanel();var buttons=new StackPanel{Orientation=Orientation.Horizontal};var add=new Button{Content="+ OBJECT"};add.Click+=(s,e)=>Author(()=>procedural.Add($"Object {procedural.Objects.Count+1}"));var duplicate=new Button{Content="DUPLICATE"};duplicate.Click+=(s,e)=>Author(()=>procedural.DuplicateSelected());var remove=new Button{Content="DELETE"};remove.Click+=(s,e)=>Author(()=>procedural.RemoveSelected());buttons.Children.Add(add);buttons.Children.Add(duplicate);buttons.Children.Add(remove);panel.Children.Add(buttons);var objects=new ListBox{ItemsSource=procedural.Objects,DisplayMemberPath="Name",Height=55};objects.SelectionChanged+=(s,e)=>{if(objects.SelectedItem is ProceduralObject o){procedural.SelectedObjectId=o.Id;BuildProceduralPanel();}};panel.Children.Add(objects);var selected=procedural.Selected;if(selected is not null){AddText(panel,"Name",selected.Name,v=>selected.Name=v);AddNumber(panel,"Base X",selected.BasePositionX,v=>selected.BasePositionX=v);AddNumber(panel,"Base Y",selected.BasePositionY,v=>selected.BasePositionY=v);AddNumber(panel,"Rotation",selected.BaseRotation,v=>selected.BaseRotation=v);AddNumber(panel,"Scale",selected.BaseScale,v=>selected.BaseScale=v);AddNumber(panel,"Opacity",selected.BaseOpacity,v=>selected.BaseOpacity=v);var addBinding=new Button{Content="+ OUTPUT BINDING"};addBinding.Click+=(s,e)=>Author(()=>selected.OutputBindings.Add(new ExpressionOutputBinding{Name="Position X",Target=OutputTarget.PositionX,ExpressionText="0"}));panel.Children.Add(addBinding);foreach(var binding in selected.OutputBindings.ToArray())BuildBinding(panel,selected,binding);}proceduralOutput=new TextBlock{Foreground=Brushes.LightBlue};panel.Children.Add(proceduralOutput);proceduralCanvas=new Canvas{Width=300,Height=180,Background=new SolidColorBrush(Color.FromRgb(11,16,21))};panel.Children.Add(proceduralCanvas);box.Content=panel;EquationsPanel.Children.Add(box);}
    void AddText(StackPanel panel,string label,string value,Action<string> assign){var row=new DockPanel();row.Children.Add(new TextBlock{Text=label,Width=80});var input=new TextBox{Text=value};input.LostFocus+=(s,e)=>Author(()=>assign(input.Text));row.Children.Add(input);panel.Children.Add(row);}
    void AddNumber(StackPanel panel,string label,double value,Action<double> assign){var row=new DockPanel();row.Children.Add(new TextBlock{Text=label,Width=80});var input=new TextBox{Text=value.ToString("G",CultureInfo.InvariantCulture)};input.LostFocus+=(s,e)=>{if(TryNumber(input.Text,out var n))Author(()=>assign(n));else input.Text=value.ToString("G",CultureInfo.InvariantCulture);};row.Children.Add(input);panel.Children.Add(row);}
    void BuildBinding(StackPanel panel,ProceduralObject obj,ExpressionOutputBinding binding){var row=new StackPanel{Orientation=Orientation.Horizontal};var enabled=new CheckBox{IsChecked=binding.IsEnabled,Content="ON"};enabled.Click+=(s,e)=>Author(()=>binding.IsEnabled=enabled.IsChecked==true);var target=new ComboBox{ItemsSource=Enum.GetValues<OutputTarget>(),SelectedItem=binding.Target,Width=85};target.SelectionChanged+=(s,e)=>{if(target.SelectedItem is OutputTarget t)Author(()=>binding.Target=t);};var mode=new ComboBox{ItemsSource=Enum.GetValues<OutputCombineMode>(),SelectedItem=binding.Mode,Width=75};mode.SelectionChanged+=(s,e)=>{if(mode.SelectedItem is OutputCombineMode m)Author(()=>binding.Mode=m);};var expression=new TextBox{Text=binding.ExpressionText,Width=90};expression.LostFocus+=(s,e)=>Author(()=>{binding.ExpressionText=expression.Text;binding.TryParse(out _);});var up=new Button{Content="↑"};up.Click+=(s,e)=>Author(()=>procedural.MoveBinding(binding,-1));var down=new Button{Content="↓"};down.Click+=(s,e)=>Author(()=>procedural.MoveBinding(binding,1));var del=new Button{Content="×"};del.Click+=(s,e)=>Author(()=>obj.OutputBindings.Remove(binding));row.Children.Add(enabled);row.Children.Add(target);row.Children.Add(mode);row.Children.Add(expression);row.Children.Add(up);row.Children.Add(down);row.Children.Add(del);panel.Children.Add(row);}
    void DrawProcedural(){if(proceduralCanvas is null)return;proceduralCanvas.Children.Clear();foreach(var obj in procedural.Objects){ProceduralOutputEvaluator.Evaluate(obj,time.Time,document.Parameters.Values);var x=150+obj.EvaluatedPositionX;var y=90-obj.EvaluatedPositionY;var shape=new Rectangle{Width=40*obj.EvaluatedScale,Height=40*obj.EvaluatedScale,Fill=new SolidColorBrush(Color.FromScRgb((float)obj.EvaluatedOpacity,(float)obj.EvaluatedColor.R,(float)obj.EvaluatedColor.G,(float)obj.EvaluatedColor.B)),RenderTransform=new RotateTransform(obj.EvaluatedRotation,20,20),Opacity=Math.Clamp(obj.EvaluatedOpacity,0,1)};Canvas.SetLeft(shape,x-shape.Width/2);Canvas.SetTop(shape,y-shape.Height/2);proceduralCanvas.Children.Add(shape);}if(procedural.Selected is{} selected&&proceduralOutput is not null)proceduralOutput.Text=$"LIVE OUTPUT  X: {selected.EvaluatedPositionX:0.##}  Y: {selected.EvaluatedPositionY:0.##}  Rotation: {selected.EvaluatedRotation:0.##}°  Scale: {selected.EvaluatedScale:0.##}  Opacity: {selected.EvaluatedOpacity:0.##}";}
}
