using Microsoft.Win32;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Shapes;
using System.Windows.Threading;

namespace EquationSynth;
public partial class MainWindow : Window {
 readonly EquationDocument document=EquationDocument.CreateDefault(); readonly GraphCamera camera=new(); readonly WaveformEngine waves=new(); readonly AudioEngine audio=new(); readonly TimeEngine time=new(); readonly DispatcherTimer timer=new(){Interval=TimeSpan.FromMilliseconds(33)}; bool dragging;Point dragStart;double dragX,dragY; (double X,double Y)? mouseWorld;
 readonly Dictionary<string,string> presets=new(){["SINE"]="sin(x)",["SQUARE-ISH"]="sin(x) + sin(3*x)/3 + sin(5*x)/5",["SAW-ISH"]="sin(x) + sin(2*x)/2 + sin(3*x)/3 + sin(4*x)/4",["AMPLITUDE MODULATION"]="sin(x) * (0.5 + 0.5*sin(t))",["PHASE MODULATION"]="sin(x + 2*sin(t))",["COMPLEX"]="sin(x*2 + sin(x*3 + t))"};
 public MainWindow(){InitializeComponent();PresetBox.ItemsSource=presets.Keys;PresetBox.SelectedIndex=0;timer.Tick+=(s,e)=>{time.Update(timer.Interval.TotalSeconds);Refresh(false);};timer.Start();document.Select(document.Equations[0]);Refresh(true);Closed+=(s,e)=>audio.Dispose();}
 EquationEntry Selected=>document.Selected??document.Equations[0];
 void Apply_Click(object s,RoutedEventArgs e)=>Apply();void EquationBox_KeyDown(object s,KeyEventArgs e){if(e.Key==Key.Enter)Apply();}
 void Apply(){var selected=Selected;var text=EquationBox.Text;var old=selected.ExpressionText;selected.ExpressionText=text;if(!selected.TryParse(out var error)){selected.ExpressionText=old;StatusText.Text="ERROR: "+error;StatusText.Foreground=Brushes.Salmon;EquationBox.Text=text;return;}StatusText.Text="✓ VALID";StatusText.Foreground=new SolidColorBrush(Color.FromRgb(116,227,155));document.ReconcileParameters();Refresh(true);}
 void Refresh(bool rebuildUi){if(rebuildUi){BuildEquationList();BuildParameters();}TimeText.Text=$"t = {time.Time:0.000}";SpeedText.Text=$"{SpeedSlider.Value:0.0}x";FrequencyText.Text=$"{FrequencySlider.Value:0} Hz";VolumeText.Text=$"{VolumeSlider.Value:0.00}";time.TimeScale=SpeedSlider.Value;DrawGraph();DrawWave();}
 void BuildEquationList(){EquationsPanel.Children.Clear();foreach(var entry in document.Equations){var row=new DockPanel{Margin=new Thickness(2),Background=entry.IsSelected?new SolidColorBrush(Color.FromRgb(35,67,82)):Brushes.Transparent};var eye=new CheckBox{IsChecked=entry.IsVisible,Content="◉",Foreground=Brushes.White,Width=28,Tag=entry};eye.Click+=(s,e)=>{entry.IsVisible=eye.IsChecked==true;DrawGraph();};var color=new Border{Width=12,Height=12,Background=Brush(entry.ColorHex),Margin=new Thickness(4)};var name=new TextBlock{Text=entry.DisplayName,Foreground=Brushes.White,VerticalAlignment=VerticalAlignment.Center};var del=new Button{Content="×",Tag=entry,Padding=new Thickness(6,0,6,0),Margin=new Thickness(2)};del.Click+=(s,e)=>{document.Select(entry);document.RemoveSelected();BuildEquationList();BuildParameters();EquationBox.Text=Selected.ExpressionText;Refresh(false);};row.Children.Add(eye);row.Children.Add(color);row.Children.Add(name);row.Children.Add(del);row.MouseLeftButtonDown+=(s,e)=>{document.Select(entry);EquationBox.Text=entry.ExpressionText;StatusText.Text="✓ VALID";BuildEquationList();Refresh(false);};EquationsPanel.Children.Add(row);}}
 void BuildParameters(){ParametersPanel.Children.Clear();foreach(var p in document.Parameters.Items){var label=new TextBlock{Text=$"{p.Name}  {p.Value:0.###}",Foreground=Brushes.White};var slider=new Slider{Minimum=p.Minimum,Maximum=p.Maximum,Value=p.Value,Tag=p,TickFrequency=p.Step};slider.ValueChanged+=(s,e)=>{if(slider.Value<p.Minimum||slider.Value>p.Maximum)return;p.Value=slider.Value;label.Text=$"{p.Name}  {p.Value:0.###}";Refresh(false);};ParametersPanel.Children.Add(label);ParametersPanel.Children.Add(slider);}}
 static Brush Brush(string hex)=>(Brush)new BrushConverter().ConvertFromString(hex)!;
 void DrawGraph(){GraphCanvas.Children.Clear();var w=GraphCanvas.ActualWidth;var h=GraphCanvas.ActualHeight;if(w<2||h<2)return;var sx=GraphSampler.NiceSpacing(camera.Width);var sy=GraphSampler.NiceSpacing(camera.Height);for(var x=Math.Ceiling(camera.XMin/sx)*sx;x<=camera.XMax;x+=sx){var p=camera.WorldToScreen(x,0,w,h);GraphCanvas.Children.Add(new Line{X1=p.X,X2=p.X,Y1=0,Y2=h,Stroke=new SolidColorBrush(Color.FromArgb(40,130,170,190))});if(Math.Abs(x)>sx/100)GraphCanvas.Children.Add(new TextBlock{Text=GraphSampler.FormatLabel(x,sx),Foreground=Brushes.Gray,FontSize=10});}for(var y=Math.Ceiling(camera.YMin/sy)*sy;y<=camera.YMax;y+=sy){var p=camera.WorldToScreen(0,y,w,h);GraphCanvas.Children.Add(new Line{X1=0,X2=w,Y1=p.Y,Y2=p.Y,Stroke=new SolidColorBrush(Color.FromArgb(40,130,170,190))});if(Math.Abs(y)>sy/100)GraphCanvas.Children.Add(new TextBlock{Text=GraphSampler.FormatLabel(y,sy),Foreground=Brushes.Gray,FontSize=10});}var origin=camera.WorldToScreen(0,0,w,h);GraphCanvas.Children.Add(new Line{X1=origin.X,X2=origin.X,Y1=0,Y2=h,Stroke=Brushes.Gray,StrokeThickness=1.5});GraphCanvas.Children.Add(new Line{X1=0,X2=w,Y1=origin.Y,Y2=origin.Y,Stroke=Brushes.Gray,StrokeThickness=1.5});foreach(var entry in document.Equations.Where(x=>x.IsVisible)){var samples=GraphSampler.Sample(entry,camera,time.Time,document.Parameters.Values,w);Polyline? line=null;double? lastY=null;foreach(var sample in samples){if(!sample.Valid){if(line is not null&&line.Points.Count>1)GraphCanvas.Children.Add(line);line=null;lastY=null;continue;}var point=camera.WorldToScreen(sample.X,entry.ParsedExpression!.Evaluate(sample.X,time.Time,document.Parameters.Values).Value,w,h);if(lastY.HasValue&&Math.Abs(point.Y-lastY.Value)>h*1.4){if(line is not null&&line.Points.Count>1)GraphCanvas.Children.Add(line);line=null;}line??=new Polyline{Stroke=Brush(entry.ColorHex),StrokeThickness=entry.IsSelected?2.5:1.5,Opacity=entry.IsSelected?1:.82};line.Points.Add(new Point(point.X,point.Y));lastY=point.Y;}if(line is not null&&line.Points.Count>1)GraphCanvas.Children.Add(line);}}
 void DrawWave(){WaveCanvas.Children.Clear();var w=WaveCanvas.ActualWidth;var h=WaveCanvas.ActualHeight;if(w<2||h<2)return;var table=waves.Generate(Selected.ParsedExpression!,time.Time,document.Parameters.Values);var zero=h/2;WaveCanvas.Children.Add(new Line{X1=0,X2=w,Y1=zero,Y2=zero,Stroke=Brushes.Gray});var p=new Polyline{Stroke=Brush(Selected.ColorHex),StrokeThickness=2};for(int i=0;i<table.Length;i++)p.Points.Add(new Point(i*w/(table.Length-1),zero-table[i]*(h*.42)));WaveCanvas.Children.Add(p);}
 void Graph_MouseWheel(object s,MouseWheelEventArgs e){var at=camera.ScreenToWorld(e.GetPosition(GraphCanvas).X,e.GetPosition(GraphCanvas).Y,GraphCanvas.ActualWidth,GraphCanvas.ActualHeight);camera.ZoomAt(e.Delta>0?.8:1.25,at.X,at.Y);Refresh(false);}void Graph_MouseDown(object s,MouseButtonEventArgs e){dragging=true;dragStart=e.GetPosition(GraphCanvas);dragX=camera.CenterX;dragY=camera.CenterY;GraphCanvas.CaptureMouse();}void Graph_MouseUp(object s,MouseButtonEventArgs e){dragging=false;GraphCanvas.ReleaseMouseCapture();}void Graph_MouseMove(object s,MouseEventArgs e){var pos=e.GetPosition(GraphCanvas);mouseWorld=camera.ScreenToWorld(pos.X,pos.Y,GraphCanvas.ActualWidth,GraphCanvas.ActualHeight);CoordinateText.Text=$"x = {mouseWorld.Value.X:0.000}    y = {mouseWorld.Value.Y:0.000}";if(!dragging)return;var dx=pos.X-dragStart.X;var dy=pos.Y-dragStart.Y;camera.Set(dragX-dx/GraphCanvas.ActualWidth*camera.Width,dragX-dx/GraphCanvas.ActualWidth*camera.Width+camera.Width,dragY+dy/GraphCanvas.ActualHeight*camera.Height,dragY+dy/GraphCanvas.ActualHeight*camera.Height-camera.Height);Refresh(false);}void Canvas_SizeChanged(object s,SizeChangedEventArgs e)=>Refresh(false);
 void AddEquation_Click(object s,RoutedEventArgs e){var e2=document.Add();document.Select(e2);EquationBox.Text=e2.ExpressionText;Refresh(true);}void Color_Click(object s,RoutedEventArgs e){if(s is Button b){Selected.ColorHex=(string)b.Tag;BuildEquationList();Refresh(false);}}
 void ViewApply_Click(object s,RoutedEventArgs e){if(double.TryParse(XMinBox.Text,out var a)&&double.TryParse(XMaxBox.Text,out var b)&&double.TryParse(YMinBox.Text,out var c)&&double.TryParse(YMaxBox.Text,out var d)&&camera.Set(a,b,c,d))Refresh(false);else StatusText.Text="ERROR: View ranges require MIN < MAX.";}void ResetView_Click(object s,RoutedEventArgs e){camera.Reset();XMinBox.Text="-10";XMaxBox.Text="10";YMinBox.Text="-5";YMaxBox.Text="5";Refresh(false);}
 void TimePlay_Click(object s,RoutedEventArgs e)=>time.Play();void TimePause_Click(object s,RoutedEventArgs e)=>time.Pause();void TimeReset_Click(object s,RoutedEventArgs e){time.Reset();Refresh(false);}void Setting_Changed(object s,RoutedPropertyChangedEventArgs<double> e){if(IsLoaded)Refresh(false);}void SoundPlay_Click(object s,RoutedEventArgs e)=>audio.Play(waves.Generate(Selected.ParsedExpression!,time.Time,document.Parameters.Values));void SoundStop_Click(object s,RoutedEventArgs e)=>audio.Stop();void Preset_Changed(object s,SelectionChangedEventArgs e){if(PresetBox.SelectedItem is string n){Selected.ExpressionText=presets[n];Selected.TryParse(out _);EquationBox.Text=Selected.ExpressionText;document.ReconcileParameters();Refresh(true);}}
 void Save_Click(object s,RoutedEventArgs e){var d=new SaveFileDialog{Filter="Equation preset|*.equation.json"};if(d.ShowDialog()==true){var st=new PresetState{Equation=Selected.ExpressionText,SelectedEquationId=document.SelectedEquationId,Frequency=FrequencySlider.Value,Volume=VolumeSlider.Value,TimeSpeed=SpeedSlider.Value,XMin=camera.XMin,XMax=camera.XMax,YMin=camera.YMin,YMax=camera.YMax,EquationEntries=document.Equations.Select(x=>new EquationData{Id=x.Id,ExpressionText=x.ExpressionText,ColorHex=x.ColorHex,IsVisible=x.IsVisible}).ToList(),Parameters=document.Parameters.Items.ToDictionary(x=>x.Name,x=>new ParameterData{Value=x.Value,Minimum=x.Minimum,Maximum=x.Maximum,Step=x.Step,DefaultValue=x.DefaultValue})};PresetService.Save(d.FileName,st);}} void Load_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Equation preset|*.equation.json"};if(d.ShowDialog()!=true)return;var st=PresetService.Load(d.FileName);if(st.EquationEntries.Count>0){document.Equations.Clear();foreach(var data in st.EquationEntries){var item=new EquationEntry{Id=data.Id,ExpressionText=data.ExpressionText,ColorHex=data.ColorHex,IsVisible=data.IsVisible};item.TryParse(out _);document.Equations.Add(item);}document.Select(document.Equations.FirstOrDefault(x=>x.Id==st.SelectedEquationId)??document.Equations[0]);}else{Selected.ExpressionText=st.Equation;Selected.TryParse(out _);}EquationBox.Text=Selected.ExpressionText;FrequencySlider.Value=st.Frequency;VolumeSlider.Value=st.Volume;SpeedSlider.Value=st.TimeSpeed;camera.Set(st.XMin,st.XMax,st.YMin,st.YMax);XMinBox.Text=st.XMin.ToString();XMaxBox.Text=st.XMax.ToString();YMinBox.Text=st.YMin.ToString();YMaxBox.Text=st.YMax.ToString();document.ReconcileParameters();Refresh(true);}
}
