using Microsoft.Win32;
using System.Diagnostics;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Shapes;
using System.Windows.Threading;

namespace EquationSynth;
public partial class MainWindow : Window {
 readonly TimeEngine time=new(); readonly WaveformEngine waves=new(); readonly AudioEngine audio=new(); Expression expression=Expression.Parse("sin(x)"); readonly ParameterSet parameters=new(); readonly DispatcherTimer timer=new(){Interval=TimeSpan.FromMilliseconds(33)}; double xmin=-10,xmax=10; bool dragging; Point dragStart; double dragXMin,dragXMax;
 readonly Dictionary<string,string> presets=new(){["SINE"]="sin(x)",["SQUARE-ISH"]="sin(x) + sin(3*x)/3 + sin(5*x)/5",["SAW-ISH"]="sin(x) + sin(2*x)/2 + sin(3*x)/3 + sin(4*x)/4",["AMPLITUDE MODULATION"]="sin(x) * (0.5 + 0.5*sin(t))",["PHASE MODULATION"]="sin(x + 2*sin(t))",["COMPLEX"]="sin(x*2 + sin(x*3 + t))"};
 public MainWindow(){InitializeComponent();PresetBox.ItemsSource=presets.Keys;PresetBox.SelectedIndex=0;timer.Tick+=(s,e)=>{time.Update(timer.Interval.TotalSeconds);Refresh();};timer.Start();Apply();Closed+=(s,e)=>audio.Dispose();}
 void Apply_Click(object s,RoutedEventArgs e)=>Apply(); void EquationBox_KeyDown(object s,KeyEventArgs e){if(e.Key==Key.Enter)Apply();}
 void Apply(){try{var next=Expression.Parse(EquationBox.Text);expression=next;parameters.Sync(next.Parameters);StatusText.Text="✓ VALID";StatusText.Foreground=new SolidColorBrush(Color.FromRgb(116,227,155));BuildParameters();Refresh();}catch(ParseException ex){StatusText.Text="ERROR: "+ex.Message;StatusText.Foreground=new SolidColorBrush(Color.FromRgb(255,123,123));}}
 void BuildParameters(){ParametersPanel.Children.Clear();foreach(var p in parameters.Items){var label=new TextBlock{Text=p.Name+"  "+p.Value.ToString("0.00"),Foreground=Brushes.White};var slider=new Slider{Minimum=p.Minimum,Maximum=p.Maximum,Value=p.Value,Tag=p,TickFrequency=p.Step};slider.ValueChanged+=(s,e)=>{p.Value=slider.Value;label.Text=p.Name+"  "+p.Value.ToString("0.00");Refresh();};ParametersPanel.Children.Add(label);ParametersPanel.Children.Add(slider);}}
 void Refresh(){TimeText.Text=$"t = {time.Time:0.000}";SpeedText.Text=$"{SpeedSlider.Value:0.0}x";FrequencyText.Text=$"{FrequencySlider.Value:0} Hz";VolumeText.Text=$"{VolumeSlider.Value:0.00}";time.TimeScale=SpeedSlider.Value;DrawGraph();DrawWave();}
 void DrawGraph(){GraphCanvas.Children.Clear();var w=GraphCanvas.ActualWidth;var h=GraphCanvas.ActualHeight;if(w<2||h<2)return;var yvalues=new List<double>();for(int i=0;i<600;i++){var r=expression.Evaluate(xmin+(xmax-xmin)*i/599,time.Time,parameters.Values);if(r.Status==ValueStatus.Valid&&double.IsFinite(r.Value)&&Math.Abs(r.Value)<1e5)yvalues.Add(r.Value);}var ymin=yvalues.Count==0?-1:yvalues.Min();var ymax=yvalues.Count==0?1:yvalues.Max();if(Math.Abs(ymax-ymin)<.01){ymin-=1;ymax+=1;}var pad=(ymax-ymin)*.12;ymin-=pad;ymax+=pad;double X(double x)=>(x-xmin)/(xmax-xmin)*w;double Y(double y)=>h-(y-ymin)/(ymax-ymin)*h;for(int i=-20;i<=20;i++){var x=i;var line=new Line{X1=X(x),X2=X(x),Y1=0,Y2=h,Stroke=new SolidColorBrush(Color.FromArgb(35,130,170,190)),StrokeThickness=1};GraphCanvas.Children.Add(line);}var axis=new Line{X1=X(0),X2=X(0),Y1=0,Y2=h,Stroke=Brushes.Gray};GraphCanvas.Children.Add(axis);var path=new Polyline{Stroke=new SolidColorBrush(Color.FromRgb(105,218,255)),StrokeThickness=2};bool connected=false;for(int i=0;i<600;i++){var r=expression.Evaluate(xmin+(xmax-xmin)*i/599,time.Time,parameters.Values);if(r.Status!=ValueStatus.Valid||!double.IsFinite(r.Value)||Math.Abs(r.Value)>1e5){connected=false;continue;}var point=new Point(X(xmin+(xmax-xmin)*i/599),Y(r.Value));if(!connected){if(path.Points.Count>0){GraphCanvas.Children.Add(path);path=new Polyline{Stroke=Brushes.Cyan,StrokeThickness=2};}connected=true;}path.Points.Add(point);}if(path.Points.Count>0)GraphCanvas.Children.Add(path);}
 void DrawWave(){WaveCanvas.Children.Clear();var w=WaveCanvas.ActualWidth;var h=WaveCanvas.ActualHeight;if(w<2||h<2)return;var table=waves.Generate(expression,time.Time,parameters.Values);var zero=h/2;WaveCanvas.Children.Add(new Line{X1=0,X2=w,Y1=zero,Y2=zero,Stroke=Brushes.Gray});var p=new Polyline{Stroke=new SolidColorBrush(Color.FromRgb(255,185,93)),StrokeThickness=2};for(int i=0;i<table.Length;i++)p.Points.Add(new Point(i*w/(table.Length-1),zero-table[i]*(h*.42)));WaveCanvas.Children.Add(p);}
 void Graph_MouseWheel(object s,MouseWheelEventArgs e){var scale=e.Delta>0?.8:1.25;var center=xmin+(xmax-xmin)*e.GetPosition(GraphCanvas).X/GraphCanvas.ActualWidth; xmin=center+(xmin-center)*scale;xmax=center+(xmax-center)*scale;Refresh();}
 void Graph_MouseDown(object s,MouseButtonEventArgs e){dragging=true;dragStart=e.GetPosition(GraphCanvas);dragXMin=xmin;dragXMax=xmax;GraphCanvas.CaptureMouse();}void Graph_MouseUp(object s,MouseButtonEventArgs e){dragging=false;GraphCanvas.ReleaseMouseCapture();}void Graph_MouseMove(object s,MouseEventArgs e){if(!dragging)return;var dx=e.GetPosition(GraphCanvas).X-dragStart.X;var amount=dx/GraphCanvas.ActualWidth*(dragXMax-dragXMin);xmin=dragXMin-amount;xmax=dragXMax-amount;Refresh();}void Canvas_SizeChanged(object s,SizeChangedEventArgs e)=>Refresh();
 void TimePlay_Click(object s,RoutedEventArgs e)=>time.Play();void TimePause_Click(object s,RoutedEventArgs e)=>time.Pause();void TimeReset_Click(object s,RoutedEventArgs e){time.Reset();Refresh();}void Setting_Changed(object s,RoutedPropertyChangedEventArgs<double> e){if(IsLoaded)Refresh();}
 void SoundPlay_Click(object s,RoutedEventArgs e)=>audio.Play(waves.Generate(expression,time.Time,parameters.Values));void SoundStop_Click(object s,RoutedEventArgs e)=>audio.Stop();void Preset_Changed(object s,SelectionChangedEventArgs e){if(PresetBox.SelectedItem is string n){EquationBox.Text=presets[n];Apply();}}
 PresetState State()=>new(){Equation=expression.Source,Frequency=FrequencySlider.Value,Volume=VolumeSlider.Value,TimeSpeed=SpeedSlider.Value,Parameters=parameters.Items.ToDictionary(p=>p.Name,p=>new ParameterData{Value=p.Value,Minimum=p.Minimum,Maximum=p.Maximum,Step=p.Step,DefaultValue=p.DefaultValue})};
 void Save_Click(object s,RoutedEventArgs e){var d=new SaveFileDialog{Filter="Equation preset|*.equation.json"};if(d.ShowDialog()==true)PresetService.Save(d.FileName,State());}void Load_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Equation preset|*.equation.json"};if(d.ShowDialog()!=true)return;try{var st=PresetService.Load(d.FileName);EquationBox.Text=st.Equation;FrequencySlider.Value=st.Frequency;VolumeSlider.Value=st.Volume;SpeedSlider.Value=st.TimeSpeed;Apply();foreach(var p in parameters.Items)if(st.Parameters.TryGetValue(p.Name,out var v)){p.Value=v.Value;p.Minimum=v.Minimum;p.Maximum=v.Maximum;p.Step=v.Step;}BuildParameters();Refresh();}catch(Exception ex){MessageBox.Show("Could not load preset: "+ex.Message,"Equation Synth",MessageBoxButton.OK,MessageBoxImage.Error);}}
}
