namespace EquationSynth;

public readonly record struct ExpressionContext(double X, double T, IReadOnlyDictionary<string,double> Parameters);
public enum OutputTarget { PositionX, PositionY, Rotation, Scale, Opacity, ColorR, ColorG, ColorB }
public enum OutputCombineMode { Replace, Add, Multiply }
public sealed class ExpressionOutputBinding {
    public Guid Id { get; set; } = Guid.NewGuid(); public string Name { get; set; } = "Output"; public OutputTarget Target { get; set; } = OutputTarget.PositionX; public OutputCombineMode Mode { get; set; } = OutputCombineMode.Replace; public string ExpressionText { get; set; } = "0"; public bool IsEnabled { get; set; } = true; public double Minimum { get; set; } = -1e9; public double Maximum { get; set; } = 1e9; [System.Text.Json.Serialization.JsonIgnore] public Expression? ParsedExpression { get; private set; }
    public bool TryParse(out string error){try{ParsedExpression=Expression.Parse(ExpressionText);error="";return true;}catch(ParseException ex){error=ex.Message;return false;}}
    public double Evaluate(ExpressionContext context,double fallback){if(ParsedExpression is null&&!TryParse(out _))return fallback;var value=ParsedExpression!.Evaluate(context.X,context.T,context.Parameters);if(value.Status!=ValueStatus.Valid||!double.IsFinite(value.Value))return fallback;return double.IsNaN(Minimum)||double.IsNaN(Maximum)||Minimum>Maximum?value.Value:Math.Clamp(value.Value,Minimum,Maximum);}
}
public sealed class ProceduralColor { public double R {get;set;}=0.41;public double G {get;set;}=.85;public double B {get;set;}=1; public ProceduralColor Clone()=>new(){R=R,G=G,B=B}; }
public sealed class ProceduralObject {
    public Guid Id {get;set;}=Guid.NewGuid();public string Name {get;set;}="Object";public double BasePositionX {get;set;} public double BasePositionY {get;set;} public double BaseRotation {get;set;} public double BaseScale {get;set;}=1;public double BaseOpacity {get;set;}=1;public ProceduralColor BaseColor {get;set;}=new();public List<ExpressionOutputBinding> OutputBindings {get;set;}=[];public bool TrailEnabled {get;set;} public int TrailLength {get;set;}=30;
    [System.Text.Json.Serialization.JsonIgnore] public double EvaluatedPositionX {get;private set;} [System.Text.Json.Serialization.JsonIgnore] public double EvaluatedPositionY {get;private set;} [System.Text.Json.Serialization.JsonIgnore] public double EvaluatedRotation {get;private set;} [System.Text.Json.Serialization.JsonIgnore] public double EvaluatedScale {get;private set;}=1; [System.Text.Json.Serialization.JsonIgnore] public double EvaluatedOpacity {get;private set;}=1; [System.Text.Json.Serialization.JsonIgnore] public ProceduralColor EvaluatedColor {get;private set;}=new(); [System.Text.Json.Serialization.JsonIgnore] public List<(double X,double Y)> Trail {get;}=[];
    internal void SetEvaluated(double x,double y,double rotation,double scale,double opacity,ProceduralColor color){EvaluatedPositionX=x;EvaluatedPositionY=y;EvaluatedRotation=rotation;EvaluatedScale=scale;EvaluatedOpacity=opacity;EvaluatedColor=color;}
    public ProceduralObject CloneAuthored(){var copy=new ProceduralObject{Id=Guid.NewGuid(),Name=Name+" Copy",BasePositionX=BasePositionX,BasePositionY=BasePositionY,BaseRotation=BaseRotation,BaseScale=BaseScale,BaseOpacity=BaseOpacity,BaseColor=BaseColor.Clone(),TrailEnabled=TrailEnabled,TrailLength=TrailLength};copy.OutputBindings=OutputBindings.Select(b=>new ExpressionOutputBinding{Id=Guid.NewGuid(),Name=b.Name,Target=b.Target,Mode=b.Mode,ExpressionText=b.ExpressionText,IsEnabled=b.IsEnabled,Minimum=b.Minimum,Maximum=b.Maximum}).ToList();return copy;}
    public void ClearRuntime(){Trail.Clear();}
}
public sealed class ProceduralScene { public List<ProceduralObject> Objects {get;set;}=[]; public Guid? SelectedObjectId {get;set;} [System.Text.Json.Serialization.JsonIgnore] public ProceduralObject? Selected=>Objects.FirstOrDefault(o=>o.Id==SelectedObjectId);public ProceduralObject Add(string name="Object"){var o=new ProceduralObject{Name=name};Objects.Add(o);SelectedObjectId=o.Id;return o;}public void RemoveSelected(){if(Selected is{} o)Objects.Remove(o);SelectedObjectId=Objects.FirstOrDefault()?.Id;}public ProceduralObject DuplicateSelected(){var copy=Selected?.CloneAuthored()??Add();if(Selected is{} source){var index=Objects.IndexOf(source);Objects.Insert(index+1,copy);SelectedObjectId=copy.Id;}return copy;}}
public static class ProceduralOutputEvaluator {
    public static void Evaluate(ProceduralObject obj,double time,IReadOnlyDictionary<string,double> parameters){var context=new ExpressionContext(0,time,parameters);var x=obj.BasePositionX;var y=obj.BasePositionY;var rotation=obj.BaseRotation;var scale=obj.BaseScale;var opacity=obj.BaseOpacity;var color=obj.BaseColor.Clone();foreach(var binding in obj.OutputBindings){if(!binding.IsEnabled)continue;var current=binding.Target switch{OutputTarget.PositionX=>x,OutputTarget.PositionY=>y,OutputTarget.Rotation=>rotation,OutputTarget.Scale=>scale,OutputTarget.Opacity=>opacity,OutputTarget.ColorR=>color.R,OutputTarget.ColorG=>color.G,OutputTarget.ColorB=>color.B,_=>0};var value=binding.Evaluate(context,current);var result=binding.Mode switch{OutputCombineMode.Replace=>value,OutputCombineMode.Add=>current+value,OutputCombineMode.Multiply=>current*value,_=>current};if(!double.IsFinite(result))result=current;switch(binding.Target){case OutputTarget.PositionX:x=Math.Clamp(result,-1e9,1e9);break;case OutputTarget.PositionY:y=Math.Clamp(result,-1e9,1e9);break;case OutputTarget.Rotation:rotation=Math.Clamp(result,-1e9,1e9);break;case OutputTarget.Scale:scale=Math.Clamp(result,0.001,1e6);break;case OutputTarget.Opacity:opacity=Math.Clamp(result,0,1);break;case OutputTarget.ColorR:color.R=Math.Clamp(result,0,1);break;case OutputTarget.ColorG:color.G=Math.Clamp(result,0,1);break;case OutputTarget.ColorB:color.B=Math.Clamp(result,0,1);break;}}obj.SetEvaluated(x,y,rotation,scale,opacity,color);if(obj.TrailEnabled){obj.Trail.Add((x,y));while(obj.Trail.Count>Math.Clamp(obj.TrailLength,1,500))obj.Trail.RemoveAt(0);}}
}
public static class ProceduralValidator {
    public static IReadOnlyList<string> Validate(ProceduralScene scene){var errors=new List<string>();var ids=new HashSet<Guid>();foreach(var obj in scene.Objects){if(!ids.Add(obj.Id))errors.Add("Duplicate procedural object ID.");if(!double.IsFinite(obj.BasePositionX)||!double.IsFinite(obj.BasePositionY)||!double.IsFinite(obj.BaseRotation)||!double.IsFinite(obj.BaseScale)||!double.IsFinite(obj.BaseOpacity))errors.Add($"Object '{obj.Name}' base values must be finite.");foreach(var binding in obj.OutputBindings){if(!binding.TryParse(out var error))errors.Add($"Object '{obj.Name}' output '{binding.Name}': {error}");if(double.IsNaN(binding.Minimum)||double.IsNaN(binding.Maximum)||binding.Minimum>binding.Maximum)errors.Add($"Object '{obj.Name}' output range is invalid.");}}return errors;}
}
