using System.Runtime.InteropServices;

namespace EquationSynth;

// Small Windows PCM streamer. Expression work happens before publication; the callback only reads arrays and fills floats.
public sealed class AudioEngine : IDisposable {
    const int Rate=48000, BufferSamples=512, BufferCount=3, FloatFormat=3, CallbackFunction=0x00030000, WomDone=0x3BD;
    readonly object lifecycle=new(); readonly WaveOutProc callback; IntPtr device; readonly byte[][] buffers=new byte[BufferCount][]; readonly GCHandle[] pins=new GCHandle[BufferCount]; readonly WaveHeader[] headers=new WaveHeader[BufferCount]; double phase; double frequency=440, targetGain=.18, gain, targetFrequency=440; float[] current=new float[WaveformEngine.SampleCount]; float[]? next; int crossfadeRemaining; int callbackIndex=-1; bool stopping;
    public const int SampleRate=Rate; public bool IsPlaying {get;private set;} public string Status {get;private set;}="STOPPED"; public int Underruns {get;private set;}
    public double Frequency {get=>targetFrequency;set=>targetFrequency=Math.Clamp(value,20,Math.Min(2000,Rate*.45));} public double Volume {get=>targetGain;set=>targetGain=Math.Clamp(value,0,.5);}
    public AudioEngine(){callback=OnWaveMessage;}
    public void Play(double[] table){SetWavetable(table);lock(lifecycle){if(IsPlaying)return;try{var format=new WaveFormat{FormatTag=FloatFormat,Channels=1,SamplesPerSec=Rate,AvgBytesPerSec=Rate*4,BlockAlign=4,BitsPerSample=32};var result=waveOutOpen(out device, -1, ref format, callback, IntPtr.Zero, CallbackFunction);if(result!=0)throw new InvalidOperationException($"Audio device could not start (code {result}).");for(var i=0;i<BufferCount;i++){buffers[i]=new byte[BufferSamples*4];pins[i]=GCHandle.Alloc(buffers[i],GCHandleType.Pinned);headers[i]=new WaveHeader{Data=pins[i].AddrOfPinnedObject(),BufferLength=(uint)buffers[i].Length};waveOutPrepareHeader(device,ref headers[i],Marshal.SizeOf<WaveHeader>());Fill(i);waveOutWrite(device,ref headers[i],Marshal.SizeOf<WaveHeader>());}gain=0;stopping=false;IsPlaying=true;Status="PLAYING";}catch{Cleanup();Status="AUDIO DEVICE UNAVAILABLE";throw;}}}
    public void SetWavetable(double[] table){if(table.Length==0)return;var copy=new float[table.Length];for(var i=0;i<table.Length;i++)copy[i]=(float)Math.Clamp(double.IsFinite(table[i])?table[i]:0,-1,1);Volatile.Write(ref next,copy);if(!IsPlaying){Volatile.Write(ref current,copy);next=null;}}
    public void Stop(){lock(lifecycle){if(!IsPlaying){Status="STOPPED";return;}stopping=true;gain=0;Cleanup();Status="STOPPED";}}
    void OnWaveMessage(IntPtr hwo,uint message,IntPtr instance,IntPtr p1,IntPtr p2){if(message==WomDone&&IsPlaying){var index=(Interlocked.Increment(ref callbackIndex)&int.MaxValue)%BufferCount;Fill(index);waveOutWrite(device,ref headers[index],Marshal.SizeOf<WaveHeader>());}}
    void Fill(int index){var table=Volatile.Read(ref current);var replacement=Volatile.Read(ref next);if(replacement is not null&&crossfadeRemaining<=0)crossfadeRemaining=Rate/20;var output=buffers[index];for(var i=0;i<BufferSamples;i++){targetFrequency=Math.Clamp(targetFrequency,20,Rate*.45);frequency+=(targetFrequency-frequency)*.0025;gain+=(targetGain-gain)*.0015;if(stopping)gain*=.98;var a=Read(table,phase);if(replacement is not null){var b=Read(replacement,phase);var alpha=1-(crossfadeRemaining/(double)(Rate/20));a=a*(1-alpha)+b*alpha;if(--crossfadeRemaining<=0){Volatile.Write(ref current,replacement);Interlocked.Exchange(ref next,null);table=replacement;}}a=Math.Tanh(a*1.4)*gain;BitConverter.TryWriteBytes(output.AsSpan(i*4,4),(float)Math.Clamp(double.IsFinite(a)?a:0,-1,1));phase+=frequency/Rate;if(phase>=1)phase-=Math.Floor(phase);}}
    static double Read(float[] table,double p){var x=p*table.Length;var i=(int)x;var f=x-i;return table[i%table.Length]*(1-f)+table[(i+1)%table.Length]*f;}
    void Cleanup(){if(device==IntPtr.Zero){IsPlaying=false;return;}try{waveOutReset(device);for(var i=0;i<headers.Length;i++){waveOutUnprepareHeader(device,ref headers[i],Marshal.SizeOf<WaveHeader>());if(pins[i].IsAllocated)pins[i].Free();}waveOutClose(device);}finally{device=IntPtr.Zero;IsPlaying=false;}}
    public void Dispose(){lock(lifecycle)Cleanup();}
    [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate void WaveOutProc(IntPtr hwo,uint msg,IntPtr instance,IntPtr p1,IntPtr p2);
    [StructLayout(LayoutKind.Sequential)] struct WaveFormat {public ushort FormatTag,Channels;public uint SamplesPerSec,AvgBytesPerSec;public ushort BlockAlign,BitsPerSample;}
    [StructLayout(LayoutKind.Sequential)] struct WaveHeader {public IntPtr Data;public uint BufferLength,BytesRecorded,User,Flags,Loops;public IntPtr Next;public IntPtr Reserved;public IntPtr Header=>Data;}
    [DllImport("winmm.dll")] static extern uint waveOutOpen(out IntPtr hwo,int device,ref WaveFormat format,WaveOutProc callback,IntPtr instance,uint flags);[DllImport("winmm.dll")]static extern uint waveOutPrepareHeader(IntPtr hwo,ref WaveHeader header,int size);[DllImport("winmm.dll")]static extern uint waveOutUnprepareHeader(IntPtr hwo,ref WaveHeader header,int size);[DllImport("winmm.dll")]static extern uint waveOutWrite(IntPtr hwo,ref WaveHeader header,int size);[DllImport("winmm.dll")]static extern uint waveOutReset(IntPtr hwo);[DllImport("winmm.dll")]static extern uint waveOutClose(IntPtr hwo);
}
