using TimeSeriesSonifier;
using System.Windows.Media;

static class Tests
{
    sealed class FakeBackend : IAudioBackend, IAudioSampleRateProvider
    {
        public int Starts; public int Stops; public bool FailStart; public bool FailStop; public Action<float[]>? Render; public int SampleRate { get; set; } = 44100;
        public void Start(Action<float[]> render) { if (FailStart) throw new InvalidOperationException("fake start"); Starts++; Render = render; var buffer = new float[32]; render(buffer); }
        public void Stop() { if (FailStop) throw new InvalidOperationException("fake stop"); Stops++; }
        public void Dispose() { }
    }
    static int count;
    static void Ok(bool value, string name) { if (!value) throw new Exception(name); count++; }
    static RawImportedData Raw(string text) => CsvImporter.Parse(text, "test.csv");
    [STAThread]
    static void Main()
    {
        var raw = Raw("year,value,note\n2000,4.2,first\n\n2001,4.5,second\n2002,bad,third\n2003,NaN,fourth\n2004,Infinity,fifth\n2005,5.1,\"quoted, value\"\n");
        Ok(raw.Headers.SequenceEqual(new[] { "year", "value", "note" }), "headers"); Ok(raw.Rows.Count == 6, "blank lines safe"); Ok(raw.Rows[0].Values[0] == "2000", "basic row"); Ok(raw.Rows[^1].Values[2] == "quoted, value", "quoted field");
        var result = DataSeriesBuilder.Build(raw, 0, 1); Ok(result.Success, "series builds"); Ok(result.ValidRows == 3 && result.SkippedRows == 3, "invalid values skipped"); Ok(raw.Rows.Count == 6, "raw remains available"); Ok(result.Series!.Points[0].Time == 2000 && result.Series.Points[^1].Time == 2005, "sorted series"); Ok(result.Series.MinimumTime == 2000 && result.Series.MaximumTime == 2005, "time bounds"); Ok(result.Series.MinimumValue == 4.2 && result.Series.MaximumValue == 5.1, "value bounds");
        var unsorted = Raw("time,value\n3,30\n1,10\n2,20\n2,25\n"); var sorted = DataSeriesBuilder.Build(unsorted, 0, 1); Ok(sorted.Series!.Points.Select(p => p.Time).SequenceEqual(new[] { 1d, 2d, 3d }), "sort and duplicate policy"); Ok(sorted.SkippedRows == 1, "duplicate skipped");
        Ok(TimeValueParser.TryParse("12.5", out var numeric) && numeric == 12.5, "numeric time"); Ok(TimeValueParser.TryParse("2001", out var year) && year == 2001, "year time"); Ok(TimeValueParser.TryParse("2024-01-02", out _), "date time"); Ok(!TimeValueParser.TryParse("not-a-time", out _), "invalid time");
        var tooSmall = DataSeriesBuilder.Build(Raw("t,v\n1,2\n"), 0, 1); Ok(!tooSmall.Success && tooSmall.Error!.Contains("two"), "minimum points"); var badColumn = DataSeriesBuilder.Build(raw, 9, 1); Ok(!badColumn.Success, "bad columns");
        var series = sorted.Series!; var interp = new SeriesInterpolator(series); var first = interp.Evaluate(1); var mid = interp.Evaluate(1.5); var last = interp.Evaluate(3); Ok(first.CurrentValue == 10 && first.LeftPointIndex == 0, "exact first"); Ok(mid.CurrentValue == 15 && mid.InterpolationFactor == .5, "midpoint"); Ok(last.CurrentValue == 30 && last.RightPointIndex == 2, "exact last"); Ok(interp.Evaluate(0).CurrentValue == 10 && interp.Evaluate(4).CurrentValue == 30, "clamps"); var uneven = new SeriesInterpolator(DataSeriesBuilder.Build(Raw("t,v\n0,0\n2,20\n10,30\n"), 0, 1).Series!); Ok(uneven.Evaluate(6).CurrentValue == 25, "uneven spacing");
        var timeline = new TimelineEngine(); timeline.SetRange(0, 10); Ok(timeline.State == TimelineState.Stopped && timeline.CurrentTime == 0, "starts stopped"); timeline.Play(); Ok(timeline.State == TimelineState.Playing, "play state"); timeline.Advance(1); Ok(timeline.CurrentTime == 1, "advance"); timeline.Pause(); var paused = timeline.CurrentTime; timeline.Advance(1); Ok(timeline.CurrentTime == paused, "pause freezes"); timeline.SeekNormalized(.5); Ok(timeline.CurrentTime == 5 && timeline.NormalizedPosition == .5, "seek"); timeline.PlaybackSpeed = 2; timeline.Play(); timeline.Advance(.5); Ok(timeline.CurrentTime == 6, "speed"); timeline.Reset(); Ok(timeline.CurrentTime == 0 && timeline.State == TimelineState.Stopped, "reset"); timeline.Play(); timeline.Advance(100); Ok(timeline.CurrentTime == 2 && timeline.State == TimelineState.Playing, "huge delta bounded"); timeline.SeekNormalized(.95); timeline.Advance(1); Ok(timeline.CurrentTime == 10 && timeline.State == TimelineState.Stopped, "end stops"); timeline.Reset(); timeline.PlaybackSpeed = 1; timeline.LoopEnabled = true; timeline.Play(); timeline.Advance(11); Ok(timeline.CurrentTime == 1 && timeline.State == TimelineState.Playing, "loop wraps"); timeline.Advance(1); Ok(timeline.CurrentTime == 2, "loop continues");
        var state = new SeriesInterpolator(series).Evaluate(2); Ok(state.LeftPointIndex == 1 && state.RightPointIndex == 2 && state.InterpolationFactor == 0, "current indexes"); Ok(state.CurrentValue == 20 && state.NormalizedPosition == .5, "current state");
        var source = DataSeriesBuilder.Build(Raw("t,v\n0,100\n1,120\n2,90\n"), 0, 1).Series!;
        var absolute = MappingEngine.Map(source, MappingMode.AbsoluteValue); Ok(absolute.Points.Select(p => p.MappedValue).SequenceEqual(new[] { 100d, 120d, 90d }), "absolute values"); Ok(absolute.Points.Select(p => p.Time).SequenceEqual(source.Points.Select(p => p.Time)), "absolute timestamps");
        var change = MappingEngine.Map(source, MappingMode.ChangeFromPrevious); Ok(change.Points.Select(p => p.MappedValue).SequenceEqual(new[] { 0d, 20d, -30d }), "change values"); Ok(change.Points[0].MappedValue == 0, "change first is zero");
        var percent = MappingEngine.Map(source, MappingMode.PercentChange); Ok(percent.Points[1].MappedValue == 20 && percent.Points[2].MappedValue == -25, "percent values"); var zero = MappingEngine.Map(DataSeriesBuilder.Build(Raw("t,v\n0,0\n1,2\n2,0\n"), 0, 1).Series!, MappingMode.PercentChange); Ok(zero.Points.All(p => double.IsFinite(p.MappedValue)) && zero.Points[1].MappedValue == 0, "zero percent safe");
        Ok(ValueNormalizer.Normalize(-30, -30, 20) == 0 && ValueNormalizer.Normalize(20, -30, 20) == 1, "normalization bounds"); Ok(ValueNormalizer.Normalize(-5, -30, 20) == .5, "normalization midpoint"); Ok(ValueNormalizer.Normalize(-40, -30, 20) == 0 && ValueNormalizer.Normalize(30, -30, 20) == 1, "normalization clamps"); Ok(ValueNormalizer.Normalize(8, 8, 8) == .5, "constant normalization"); Ok(ValueNormalizer.Normalize(double.NaN, 0, 1) == .5 && ValueNormalizer.Normalize(double.PositiveInfinity, 0, 1) == .5, "nonfinite normalization"); Ok(ValueNormalizer.MapRange(.5, 10, 20) == 15, "range mapping");
        var mappedMid = new MappedSeriesInterpolator(MappingEngine.Map(source, MappingMode.ChangeFromPrevious)).Evaluate(.5); Ok(mappedMid.CurrentMappedValue == 10 && mappedMid.CurrentOriginalValue == 110, "mapped interpolation"); Ok(mappedMid.CurrentNormalizedValue == .8, "mapped normalized state"); Ok(mappedMid.LeftPointIndex == 0 && mappedMid.RightPointIndex == 1, "mapped indexes");
        var json = JsonImporter.Parse("[{\"Year\":2000,\"Population\":4.2,\"Label\":\"first\"},{\"Year\":2001,\"Population\":4.5},{\"Year\":2002,\"Label\":null}]", "population.json"); Ok(json.Headers.Contains("Year") && json.Headers.Contains("Population") && json.Headers.Contains("Label"), "json headers union"); Ok(json.Rows.Count == 3 && json.Rows[0].Values[1] == "4.2", "json array objects"); Ok(json.Rows[1].Values[2] == "", "json missing property"); Ok(json.Rows[2].Values[1] == "", "json null property"); Ok(DataSeriesBuilder.Build(json, 0, 1).Success, "json shared series builder"); var wrapped = JsonImporter.Parse("{\"data\":[{\"time\":0,\"value\":1},{\"time\":1,\"value\":2}]}", "wrapped.json"); Ok(wrapped.Rows.Count == 2, "json wrapped array"); try { JsonImporter.Parse("not json"); Ok(false, "malformed json safe"); } catch (System.Text.Json.JsonException) { Ok(true, "malformed json safe"); } try { JsonImporter.Parse("[]"); Ok(false, "empty json safe"); } catch (InvalidDataException) { Ok(true, "empty json safe"); }
        Ok(PitchMapper.Map(0) == 110 && PitchMapper.Map(1) == 1760, "pitch endpoints"); Ok(Math.Abs(PitchMapper.Map(.5) - 440) < .0001, "pitch geometric midpoint"); Ok(PitchMapper.Map(-1) == 110 && PitchMapper.Map(2) == 1760, "pitch clamps"); Ok(double.IsFinite(PitchMapper.Map(double.NaN)) && PitchMapper.Map(double.NaN) == 440, "pitch nonfinite safe"); Ok(PitchMapper.Map(0, 0, -2) == 110, "invalid pitch range safe"); Ok(PitchMapper.Map(1, 19999, 50000) <= PitchMapper.MaximumSafeFrequency + .0001, "pitch upper bound");
        var oscillator = new Oscillator(); foreach (var waveform in Enum.GetValues<WaveformType>()) { oscillator.Waveform = waveform; var samples = Enumerable.Range(0, 100).Select(_ => oscillator.NextSample(440)).ToArray(); Ok(samples.All(x => float.IsFinite(x) && x is >= -1 and <= 1), $"{waveform} oscillator"); } var phase = oscillator.Phase; oscillator.NextSample(220); Ok(oscillator.Phase != phase, "oscillator phase continues");
        var smoother = new ParameterSmoother(100); smoother.SetTarget(1000); var rising = smoother.Advance(.01); Ok(rising > 100 && rising < 1000, "frequency smooth up"); smoother.SetTarget(50); var falling = smoother.Advance(.01); Ok(falling < rising && falling > 50, "frequency smooth down"); Ok(double.IsFinite(smoother.Advance(double.NaN)), "smoother invalid delta");
        var fake = new FakeBackend(); var lifecycle = new AudioLifecycle(fake); Ok(lifecycle.State == AudioEngineState.Stopped, "audio starts stopped"); Ok(lifecycle.Start() && lifecycle.State == AudioEngineState.Running && fake.Starts == 1, "audio start"); Ok(lifecycle.Start() && fake.Starts == 1, "audio start twice"); lifecycle.Stop(); lifecycle.Stop(); Ok(lifecycle.State == AudioEngineState.Stopped && fake.Stops == 1, "audio stop twice"); Ok(lifecycle.Start() && lifecycle.State == AudioEngineState.Running, "audio restart"); lifecycle.Dispose(); lifecycle.Dispose(); Ok(lifecycle.State == AudioEngineState.Disposed, "audio dispose twice"); Ok(!lifecycle.Start(), "disposed cannot restart");
        var failed = new FakeBackend { FailStart = true }; var failedLifecycle = new AudioLifecycle(failed); Ok(!failedLifecycle.Start() && failedLifecycle.State == AudioEngineState.Faulted, "audio start failure safe"); failedLifecycle.Stop(); Ok(failedLifecycle.State is AudioEngineState.Stopped or AudioEngineState.Faulted, "fault stop safe"); var faultStop = new FakeBackend { FailStop = true }; var faulted = new AudioLifecycle(faultStop); Ok(faulted.Start(), "audio runtime start"); faulted.Stop(); Ok(faulted.State == AudioEngineState.Faulted, "audio runtime failure safe"); var engineBackend = new FakeBackend(); using var engine = new AudioEngine(engineBackend); engine.SetTargetFrequencyFromNormalized(.5, 110, 1760); Ok(Math.Abs(engine.TargetFrequency - 440) < .0001, "state to pitch"); Ok(engine.Start() && engine.State == AudioEngineState.Running, "engine running"); Ok(engine.SampleRate == 44100, "actual backend sample rate propagated"); engine.SetTargetFrequencyFromNormalized(1, 110, 1760); engine.Stop(); engine.Stop(); Ok(engine.State == AudioEngineState.Stopped && engineBackend.Stops == 1, "engine stop idempotent");
        var pauseBackend = new FakeBackend(); using var pauseEngine = new AudioEngine(pauseBackend); Ok(pauseEngine.Start(), "pause engine starts"); pauseEngine.Pause(); Ok(pauseEngine.State == AudioEngineState.Paused, "pause state keeps backend"); var silent = new float[32]; pauseBackend.Render!(silent); Ok(silent.All(x => x == 0), "pause renders silence"); pauseEngine.Start(); Ok(pauseEngine.State == AudioEngineState.Running && pauseBackend.Starts == 1, "resume does not reopen backend"); pauseEngine.Stop();
        Ok(IconScaleMapper.Map(0, .5, 1.5) == .5 && IconScaleMapper.Map(1, .5, 1.5) == 1.5, "icon scale endpoints"); Ok(IconScaleMapper.Map(.5, .5, 1.5) == 1 && IconScaleMapper.Map(-1, .5, 1.5) == .5 && IconScaleMapper.Map(2, .5, 1.5) == 1.5, "icon scale clamp"); Ok(IconScaleMapper.Map(double.NaN, .5, 1.5) == 1, "icon scale nonfinite safe"); Ok(IconScaleMapper.Map(.5, -1, double.PositiveInfinity) == 1, "icon invalid scales safe"); var iconSettings = new IconSettings(); Ok(iconSettings.ScalingEnabled && iconSettings.MinimumScale == .5 && iconSettings.MaximumScale == 1.5 && iconSettings.Validate(out _), "icon defaults valid"); iconSettings.Enabled = true; var oldMin = iconSettings.MinimumScale; iconSettings.Enabled = false; Ok(iconSettings.MinimumScale == oldMin, "icon enable preserves settings"); iconSettings.ScalingEnabled = false; Ok(iconSettings.MinimumScale == oldMin && iconSettings.MaximumScale == 1.5, "icon scale toggle preserves range"); Ok(iconSettings.DisplayMode == IconDisplayMode.CenterFixed, "icon fixed center mode");
        var iconSeries = MappingEngine.Map(source, MappingMode.AbsoluteValue); var iconState = new MappedSeriesInterpolator(iconSeries).Evaluate(1); Ok(iconState.CurrentNormalizedValue == ValueNormalizer.Normalize(120, 90, 120), "icon uses current normalized value"); Ok(IconScaleMapper.Map(iconState.CurrentNormalizedValue, .5, 1.5) == 1.5, "icon scale integration"); var constantIconSeries = MappingEngine.Map(DataSeriesBuilder.Build(Raw("t,v\n0,4\n1,4\n"), 0, 1).Series!, MappingMode.AbsoluteValue); var constantIconState = new MappedSeriesInterpolator(constantIconSeries).Evaluate(.5); Ok(constantIconState.CurrentNormalizedValue == .5 && IconScaleMapper.Map(.5, .5, 1.5) == 1, "constant icon midpoint"); Ok(iconSettings.DisplayMode == IconDisplayMode.CenterFixed, "icon defaults to fixed center"); iconSettings.MinimumScale = 2; iconSettings.MaximumScale = 1; Ok(!iconSettings.Validate(out _), "invalid icon range rejected"); try { IconImageLoader.Load(Path.Combine(Path.GetTempPath(), "missing-time-series-sonifier-image.png")); Ok(false, "missing image safe"); } catch (FileNotFoundException) { Ok(true, "missing image safe"); }
        Ok(SpectrumPalette.Background == Brushes.White && ((SolidColorBrush)SpectrumPalette.Grid).Color == Color.FromRgb(225, 231, 236) && ((SolidColorBrush)SpectrumPalette.Accent).Color == Color.FromRgb(32, 164, 100), "light spectrum palette"); Ok(SpectrumAnalyzer.HannWindow(8).Length == 8, "hann length"); var hann = SpectrumAnalyzer.HannWindow(9); Ok(Math.Abs(hann[0]) < 1e-12 && Math.Abs(hann[^1]) < 1e-12, "hann endpoints"); Ok(hann[4] > .99, "hann center"); Ok(SpectrumAnalyzer.BinFrequency(1024, 48000, 2048) == 24000, "nyquist frequency"); Ok(Math.Abs(SpectrumAnalyzer.BinFrequency(10, 48000, 2048) - 234.375) < .001, "bin frequency"); Ok(SpectrumAnalyzer.ToDb(0) == SpectrumAnalyzer.FloorDb && double.IsFinite(SpectrumAnalyzer.ToDb(double.NaN)), "db silence finite");
        try { using var invalidAnalyzer = new SpectrumAnalyzer(); invalidAnalyzer.SetFftSize(1000); Ok(false, "invalid fft size rejected"); } catch (ArgumentOutOfRangeException) { Ok(true, "invalid fft size rejected"); }
        using var analyzer = new SpectrumAnalyzer(); Ok(!analyzer.Enabled && analyzer.FftSize == 2048, "analyzer starts disabled"); analyzer.Enable(); analyzer.Enable(); var silence = new float[2048]; var silenceFrame = analyzer.Analyze(silence)!; Ok(silenceFrame.Frequencies.Length == 1025 && silenceFrame.Decibels.All(double.IsFinite), "silence spectrum finite"); Ok(silenceFrame.Decibels.All(x => x <= 0 && x >= SpectrumAnalyzer.FloorDb), "spectrum db floor"); analyzer.Disable(); Ok(analyzer.Analyze(silence) is null, "disabled analyzer idle"); analyzer.Enable(); analyzer.SetFftSize(1024); Ok(analyzer.FftSize == 1024 && analyzer.Analyze(new float[1024]) is not null, "fft size change safe"); analyzer.Disable(); analyzer.Enable(); analyzer.Disable(); analyzer.Enable(); Ok(analyzer.Analyze(new float[1024]) is not null, "analyzer enable cycle"); analyzer.Dispose(); analyzer.Dispose(); Ok(analyzer.Analyze(new float[1024]) is null, "analyzer dispose safe");
        var ring = new AudioSampleRingBuffer(8); Ok(ring.Count == 0 && !ring.TryCopyLatest(new float[4]), "empty sample buffer safe"); ring.Write(new float[] { .1f, .2f, .3f, .4f }); var latest = new float[4]; Ok(ring.TryCopyLatest(latest) && latest.SequenceEqual(new float[] { .1f, .2f, .3f, .4f }), "sample buffer latest"); ring.Write(new float[] { .5f, .6f, .7f, .8f, .9f, 1f }); var wrappedSamples = new float[4]; Ok(ring.TryCopyLatest(wrappedSamples) && wrappedSamples.SequenceEqual(new float[] { .7f, .8f, .9f, 1f }), "sample buffer wrap"); ring.Write(new float[] { float.NaN, float.PositiveInfinity }); var sanitized = new float[4]; ring.TryCopyLatest(sanitized); Ok(sanitized[^2] == 0 && sanitized[^1] == 0 && ring.Capacity == 8, "sample buffer bounded and sanitized"); ring.Clear(); Ok(ring.Count == 0 && !ring.TryCopyLatest(new float[1]), "sample buffer clear");
        static float[] Tone(double frequency, int size, WaveformType waveform) { var oscillator = new Oscillator { Waveform = waveform }; return Enumerable.Range(0, size).Select(_ => oscillator.NextSample(frequency)).ToArray(); }
        using var toneAnalyzer = new SpectrumAnalyzer(true); toneAnalyzer.SetFftSize(2048); var exact = toneAnalyzer.Analyze(Tone(SpectrumAnalyzer.BinFrequency(10, 48000, 2048), 2048, WaveformType.Sine))!; Ok(exact.Decibels.All(double.IsFinite), "fft output finite"); var exactPeak = Array.IndexOf(exact.Decibels, exact.Decibels.Max()); Ok(exactPeak == 10, "known sine dominant bin"); var sine440 = toneAnalyzer.Analyze(Tone(440, 2048, WaveformType.Sine))!; Ok(Math.Abs(sine440.Frequencies[Array.IndexOf(sine440.Decibels, sine440.Decibels.Max())] - 440) < 50, "440 sine peak"); var square = toneAnalyzer.Analyze(Tone(440, 2048, WaveformType.Square))!; var saw = toneAnalyzer.Analyze(Tone(440, 2048, WaveformType.Saw))!; var triangle = toneAnalyzer.Analyze(Tone(440, 2048, WaveformType.Triangle))!; Ok(square.Decibels.Skip(3).Max() > SpectrumAnalyzer.FloorDb, "square harmonics"); Ok(saw.Decibels.Skip(3).Max() > SpectrumAnalyzer.FloorDb, "saw harmonics"); Ok(triangle.Decibels.All(double.IsFinite), "triangle finite");
        var tapBackend = new FakeBackend(); using var tapEngine = new AudioEngine(tapBackend); Ok(tapEngine.Start() && tapEngine.SampleBuffer.Count == 32, "generated samples reach tap"); var tapped = new float[32]; Ok(tapEngine.SampleBuffer.TryCopyLatest(tapped) && tapped.All(float.IsFinite), "tap samples finite"); tapEngine.Volume = 0; tapBackend.Render!(new float[32]); Ok(tapEngine.SampleBuffer.Count == 64 && tapEngine.SampleBuffer.TryCopyLatest(tapped) && tapped.All(x => x == 0), "volume zero tap safe"); tapEngine.Stop(); Ok(tapEngine.State == AudioEngineState.Stopped && tapEngine.SampleBuffer.Count == 0, "audio stop clears tap"); Ok(tapEngine.Start() && tapEngine.SampleBuffer.Count == 32, "audio restart tap safe"); tapEngine.Stop();
        var coordinatorTimeline = new TimelineEngine(); var coordinatorBackend = new FakeBackend(); using var coordinatorAudio = new AudioEngine(coordinatorBackend); var coordinator = new PlaybackCoordinator(coordinatorTimeline, coordinatorAudio); coordinator.SetSeries(absolute); coordinator.SetPitchRange(110, 1760); coordinator.SetAudioEnabled(false); coordinator.Play(); Ok(coordinatorTimeline.State == TimelineState.Playing && coordinatorBackend.Starts == 0, "play starts visual-only timeline"); coordinator.Pause(); Ok(coordinatorTimeline.State == TimelineState.Paused, "coordinator pause"); coordinator.SeekNormalized(1); Ok(coordinator.CurrentDataState.CurrentNormalizedValue == 0, "coordinator seek shared state"); coordinator.Reset(); Ok(coordinatorTimeline.State == TimelineState.Stopped && coordinatorAudio.State == AudioEngineState.Stopped, "coordinator reset"); coordinator.SetAudioEnabled(true); coordinator.Play(); Ok(coordinatorTimeline.State == TimelineState.Playing && coordinatorBackend.Starts == 1, "play starts enabled audio"); var startsBeforeRepeat = coordinatorBackend.Starts; coordinator.Play(); Ok(coordinatorBackend.Starts == startsBeforeRepeat, "repeated play does not restart audio"); coordinator.Pause(); Ok(coordinatorTimeline.State == TimelineState.Paused && coordinatorAudio.State == AudioEngineState.Paused, "coordinator pause silences audio"); coordinator.Play(); Ok(coordinatorTimeline.State == TimelineState.Playing && coordinatorAudio.State == AudioEngineState.Running && coordinatorBackend.Starts == startsBeforeRepeat, "coordinator resume reuses audio"); var targetBeforeSpeed = coordinatorAudio.TargetFrequency; coordinator.SetPlaybackSpeed(4); Ok(coordinatorAudio.TargetFrequency == targetBeforeSpeed, "speed does not alter pitch"); coordinator.SetAudioEnabled(false); Ok(coordinatorTimeline.State == TimelineState.Playing && coordinatorAudio.State == AudioEngineState.Stopped, "disable audio preserves playback"); coordinator.SetAudioEnabled(true); Ok(coordinatorBackend.Starts == 2, "enable audio joins active playback"); coordinator.Reset(); Ok(coordinatorAudio.State == AudioEngineState.Stopped, "coordinator shutdown state safe"); var failedCoordinatorAudio = new AudioEngine(new FakeBackend { FailStart = true }); var failedCoordinator = new PlaybackCoordinator(new TimelineEngine(), failedCoordinatorAudio); failedCoordinator.SetSeries(absolute); failedCoordinator.SetAudioEnabled(true); failedCoordinator.Play(); Ok(failedCoordinator.Timeline.State == TimelineState.Playing && failedCoordinatorAudio.State == AudioEngineState.Faulted, "audio failure preserves playback"); failedCoordinatorAudio.Dispose();
        Ok(IconOpacity.Clamp(IconOpacity.Default) == .35 && IconOpacity.Clamp(0) == 0 && IconOpacity.Clamp(1) == 1, "icon opacity range"); Ok(IconOpacity.Clamp(-1) == 0 && IconOpacity.Clamp(2) == 1 && IconOpacity.Clamp(double.NaN) == .35, "icon opacity safe");
        Ok(OutputProfile.Vertical.Width == 1080 && OutputProfile.Vertical.Height == 1920, "vertical output profile"); Ok(OutputProfile.Square.Width == 1080 && OutputProfile.Square.Height == 1080, "square output profile"); Ok(OutputProfile.Horizontal.Width == 1920 && OutputProfile.Horizontal.Height == 1080, "horizontal output profile"); Ok(OutputProfile.All.Count == 3 && OutputProfile.All[0] == OutputProfile.Vertical, "output profiles available"); Ok(OutputFrameTiming.FrameTime(0, 30) == 0 && Math.Abs(OutputFrameTiming.FrameTime(30, 30) - 1) < .000001, "deterministic frame timing"); Ok(OutputFrameTiming.FrameCount(10, 30) == 300 && OutputFrameTiming.FrameCount(10, 60) == 600, "deterministic frame count"); Ok(OutputFrameTiming.FrameCount(-1, 30) == 0, "invalid frame timing safe"); var cube = IconImageLoader.CreateDefaultCube(); Ok(cube is not null && cube.CanFreeze, "default cube placeholder"); var wavPath = Path.Combine(Path.GetTempPath(), "time-series-sonifier-test.wav"); try { var sampleCount = OfflineAudioRenderer.RenderWav(wavPath, absolute, WaveformType.Sine, .25, .1, false, 8000); Ok(sampleCount == 800 && new FileInfo(wavPath).Length == 1644, "offline audio sample count"); } finally { if (File.Exists(wavPath)) File.Delete(wavPath); } var ffmpegArgs = VideoEncoderService.BuildArguments("frames-%05d.png", "audio.wav", "out.mp4", 1080, 1920, 30, true); Ok(ffmpegArgs.Contains("libx264") && ffmpegArgs.Contains("yuv420p") && ffmpegArgs.Contains("aac") && ffmpegArgs.Contains("1080:1920"), "encoder arguments"); Ok(VideoEncoderService.Quote("a path\\file.mp4").StartsWith("\"") && VideoEncoderService.Quote("a path\\file.mp4").EndsWith("\""), "encoder path quoting");
        Ok(Math.Abs(PitchMapper.Map(.25) - 220) < .0001 && Math.Abs(PitchMapper.Map(.5) - 440) < .0001 && Math.Abs(PitchMapper.Map(.75) - 880) < .0001, "pitch progression");
        var labelState = CurrentDataState.Empty; var labelScene = new PresentationScene(null, labelState, null, .35, .5, 1.5, null, "Year", "Population"); Ok(ColumnLabel.Format(labelScene.TimeColumnName, "TIME") == "YEAR" && ColumnLabel.Format(labelScene.ValueColumnName, "VALUE") == "POPULATION", "presentation labels"); Ok(ColumnLabel.Format("Medical_Unit", "VALUE") == "MEDICAL_UNIT", "column label semantics"); var pitchBackend = new FakeBackend(); using var pitchEngine = new AudioEngine(pitchBackend); pitchEngine.Start(); pitchEngine.SetTargetFrequencyFromNormalized(0, 110, 1760); pitchBackend.Render!(new float[512]); var low = pitchEngine.CurrentFrequency; pitchEngine.SetTargetFrequencyFromNormalized(1, 110, 1760); pitchBackend.Render!(new float[512]); Ok(pitchEngine.TargetFrequency == 1760 && pitchEngine.CurrentFrequency > low, "live pitch follows target"); pitchEngine.Stop();
        var densePoints = Enumerable.Range(0, 100000).Select(i => new MappedDataPoint(i, i, i == 50000 ? 1000 : Math.Sin(i * .01), i, i.ToString())).ToArray(); var dense = new MappedDataSeries { Name = "dense", Mode = MappingMode.AbsoluteValue, Points = densePoints }; var display = GraphSamplingService.Sample(dense, 1000); Ok(display.Count <= 3000 && display[0].Time == 0 && display[^1].Time == 99999, "dense display sampling budget and endpoints"); Ok(display.Any(p => p.Value == 1000), "dense sampling preserves spike"); var cache = new GraphRenderCache(); cache.Get(dense, 1000); cache.Get(dense, 1000); Ok(cache.RebuildCount == 1, "graph cache reuses unchanged viewport"); cache.Get(dense, 1200); Ok(cache.RebuildCount == 2, "graph cache invalidates width"); var ticks = AxisTickGenerator.NiceTicks(-3, 9); Ok(ticks.Count is >= 4 and <= 12 && ticks.Contains(0), "axis ticks across zero"); Ok(AxisLabelFormatter.Number(1_250_000) == "1.25M" && AxisLabelFormatter.Number(.025) == "0.025", "axis number formatting"); var fps = new FpsTracker(); fps.TryUpdate(TimeSpan.FromSeconds(.1), out _); Ok(fps.TryUpdate(TimeSpan.FromSeconds(.7), out var measuredFps) && double.IsFinite(measuredFps) && measuredFps > 0, "fps tracker finite"); Console.WriteLine($"Time-Series Sonifier tests passed: {count}");
        var fpsSixty = new FpsTracker(); fpsSixty.TryUpdate(TimeSpan.Zero, out _); var sixtyValue = 0d; for (var i = 1; i <= 60; i++) if (fpsSixty.TryUpdate(TimeSpan.FromSeconds(i / 60d), out var currentFps)) sixtyValue = currentFps; Ok(sixtyValue > 50 && sixtyValue < 70, "fps 60 frame rate"); fpsSixty.Reset(); Ok(!fpsSixty.TryUpdate(TimeSpan.Zero, out _), "fps reset");
        Ok(GraphReveal.Progress(0, GraphRevealMode.Progressive) == GraphReveal.InitialFraction, "reveal initial fraction"); Ok(Math.Abs(GraphReveal.Progress(.5, GraphRevealMode.Progressive) - .5) < .0001, "reveal follows timeline"); Ok(GraphReveal.Progress(0, GraphRevealMode.FullGraph) == 1, "full graph reveal"); Ok(GraphReveal.Progress(double.NaN, GraphRevealMode.Progressive) == GraphReveal.InitialFraction, "reveal nonfinite safe"); var light = ThemePalette.For(AppearanceMode.Light); var dark = ThemePalette.For(AppearanceMode.Dark); Ok(light.GraphBackground == Colors.White && dark.GraphBackground != light.GraphBackground && dark.PrimaryText != light.PrimaryText, "theme palettes distinct"); var themedCache = new GraphRenderCache(); themedCache.Get(dense, 1000, "TIME", "VALUE", AppearanceMode.Light); themedCache.Get(dense, 1000, "TIME", "VALUE", AppearanceMode.Light); Ok(themedCache.RebuildCount == 1, "theme cache reuse"); themedCache.Get(dense, 1000, "TIME", "VALUE", AppearanceMode.Dark); Ok(themedCache.RebuildCount == 2, "theme cache invalidates once");
        Ok(Math.Abs(GraphReveal.VisibleFraction(0, GraphRevealMode.Progressive) - .04) < .0001, "frame starts at four percent"); Ok(Math.Abs(GraphReveal.VisibleFraction(.5, GraphRevealMode.Progressive) - .52) < .0001, "frame midpoint"); Ok(GraphReveal.VisibleFraction(1, GraphRevealMode.Progressive) == 1 && GraphReveal.VisibleFraction(-1, GraphRevealMode.Progressive) == .04, "frame bounds"); Ok(GraphReveal.VisibleFraction(.5, GraphRevealMode.FullGraph) == 1, "full frame mode"); var resources = new System.Windows.ResourceDictionary(); var frozenBrush = new SolidColorBrush(Colors.White); frozenBrush.Freeze(); resources["GraphBackgroundBrush"] = frozenBrush; var manager = new ThemeManager(); manager.SetMode(AppearanceMode.Dark); manager.ApplyResources(resources); Ok(resources["GraphBackgroundBrush"] is SolidColorBrush replacement && replacement.Color != Colors.White, "frozen theme resource replaced safely");
        var earlyDomain = DynamicGraphDomain.Calculate(dense, new SeriesInterpolator(new DataSeries { Name = "dense", Points = densePoints.Select(p => new DataPoint(p.Time, p.OriginalValue, p.OriginalRowIndex, p.OriginalTimeText)).ToArray() }).Evaluate(0), 0); var middleDomain = DynamicGraphDomain.Calculate(dense, new CurrentDataState(.5, 49999.5, 0, 0, 0, 0) { CurrentMappedValue = 0 }, .5); var finalDomain = DynamicGraphDomain.Calculate(dense, CurrentDataState.Empty, 1); Ok(earlyDomain.VisibleStartTime == dense.MinimumTime && earlyDomain.VisibleEndTime < dense.MaximumTime, "dynamic domain initial span"); Ok(middleDomain.VisibleEndTime > earlyDomain.VisibleEndTime && finalDomain.VisibleEndTime == dense.MaximumTime, "dynamic domain expands"); Ok(DynamicGraphDomain.LastIndexAtOrBefore(dense.Points, 500) == 500, "dynamic domain filters future points"); Ok(finalDomain.VisibleMinY <= 0 && finalDomain.VisibleMaxY >= 1000, "dynamic domain prefix extrema");
        using (var defaultAudio = new AudioEngine(new FakeBackend())) { var defaults = new PlaybackCoordinator(new TimelineEngine(), defaultAudio); Ok(defaults.AudioEnabled, "audio enabled by default"); }
        using (var defaultSpectrum = new SpectrumAnalyzer(true)) { Ok(defaultSpectrum.Enabled, "spectrum enabled by default"); }
        Ok(new ThemeManager().Mode == AppearanceMode.Light, "default theme is light"); Ok(new GraphSurface().RevealMode == GraphRevealMode.Progressive, "default graph mode is progressive");
        Ok(DatasetNameFormatter.Format("AMZN_stock_data.csv") == "AMZN STOCK DATA", "dataset title underscores and extension"); Ok(DatasetNameFormatter.Format("world-population.csv") == "WORLD POPULATION", "dataset title hyphens"); Ok(DatasetNameFormatter.Format("tesla-price-history.json") == "TESLA PRICE HISTORY", "dataset title json"); Ok(DatasetNameFormatter.Format("C:\\data\\AMZN_stock_data.csv") == "AMZN STOCK DATA", "dataset title excludes directory"); Ok(DatasetNameFormatter.Format("   ") == "DATA VISUALIZATION", "dataset title fallback");
        var verticalLayout = PresentationLayout.Calculate(new System.Windows.Rect(0, 0, 300, 533), OutputProfile.Vertical); var squareLayout = PresentationLayout.Calculate(new System.Windows.Rect(0, 0, 500, 500), OutputProfile.Square); var horizontalLayout = PresentationLayout.Calculate(new System.Windows.Rect(0, 0, 800, 450), OutputProfile.Horizontal); Ok(verticalLayout.Chart.Width > 250 && verticalLayout.Chart.Height > 250, "vertical output chart is dominant"); Ok(verticalLayout.Title.Bottom < verticalLayout.Chart.Top && verticalLayout.Chart.Bottom < verticalLayout.Readouts.Top && verticalLayout.Readouts.Bottom < verticalLayout.Spectrum.Top, "vertical output regions do not overlap"); Ok(squareLayout.Chart.Width > 400 && squareLayout.Chart.Bottom < squareLayout.Spectrum.Top, "square output layout bounds"); Ok(horizontalLayout.Chart.Width > 700 && horizontalLayout.Chart.Bottom < horizontalLayout.Spectrum.Top, "horizontal output layout bounds");
        var titledScene = new PresentationScene(dense, CurrentDataState.Empty, null, .35, .5, 1.5, null, DatasetDisplayName: "AMZN STOCK DATA"); Ok(titledScene.DatasetDisplayName == "AMZN STOCK DATA" && PresentationSceneTitle.For(titledScene) == "AMZN STOCK DATA", "presentation scene carries dataset title"); Ok(PresentationSceneTitle.For(new PresentationScene(null, CurrentDataState.Empty, null, .35, .5, 1.5, null)) == "DATA VISUALIZATION", "presentation title fallback"); Ok(PresentationSceneTitle.For(new PresentationScene(dense, CurrentDataState.Empty, null, .35, .5, 1.5, null)) == "DENSE", "renderer uses dataset title"); Ok(PresentationText.Time(63839664000) != "6.3839664E+10", "presentation time is formatted");
        var verticalTypography = PresentationTypography.For(new System.Windows.Rect(0, 0, 1080, 1920), OutputProfile.Vertical); var squareTypography = PresentationTypography.For(new System.Windows.Rect(0, 0, 1080, 1080), OutputProfile.Square); var horizontalTypography = PresentationTypography.For(new System.Windows.Rect(0, 0, 1920, 1080), OutputProfile.Horizontal); Ok(verticalTypography.Title >= 40 && verticalTypography.AxisTick >= 24 && verticalTypography.AxisTitle >= 24 && verticalTypography.PrimaryReadout >= 32, "vertical mobile typography scale"); Ok(verticalTypography.SecondaryReadout < verticalTypography.PrimaryReadout, "secondary typography hierarchy"); Ok(squareTypography.Title > 0 && horizontalTypography.AxisTick > 0, "profile typography scales");
        foreach (var waveform in Enum.GetValues<WaveformType>()) { var snapshot = WaveformSnapshot.Create(waveform, 440, .5, 0, 256); Ok(snapshot.Samples.Count == 256 && snapshot.Samples.All(float.IsFinite), $"{waveform} waveform finite"); } var lowWave = WaveformSnapshot.Create(WaveformType.Sine, 110, 1, 0, 256); var highWave = WaveformSnapshot.Create(WaveformType.Sine, 880, 1, 0, 256); var quietWave = WaveformSnapshot.Create(WaveformType.Sine, 440, 0, 0, 256); Ok(lowWave.Samples.Count <= 512 && highWave.Samples.Count <= 512, "waveform sample bound"); Ok(highWave.Samples.Zip(highWave.Samples.Skip(1), (a, b) => Math.Abs(b - a)).Sum() > lowWave.Samples.Zip(lowWave.Samples.Skip(1), (a, b) => Math.Abs(b - a)).Sum(), "frequency changes waveform density"); Ok(quietWave.Samples.All(x => x == 0), "amplitude changes waveform height"); Ok(WaveformSnapshot.Create(WaveformType.Saw, double.NaN, double.NaN, double.NaN).Samples.All(float.IsFinite), "invalid waveform inputs safe"); var deterministicA = WaveformSnapshot.Create(WaveformType.Triangle, 220, .25, .3); var deterministicB = WaveformSnapshot.Create(WaveformType.Triangle, 220, .25, .3); Ok(deterministicA.Samples.SequenceEqual(deterministicB.Samples), "waveform deterministic phase");
        Console.WriteLine($"Time-Series Sonifier final checks passed: {count}");
    }
}
