<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>ParticleModelViewer</RootNamespace>
    <AssemblyName>BounceSimulator</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <None Update="radial_gradient.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
