using System.Numerics;
using CreatureConstructionLab.Editor;

var passed = 0;
Run("starts empty", () => { var s = new EditorState(); Check(s.Creature.Nodes.Count == 0 && s.Creature.Connections.Count == 0); });
Run("first node can be created", () => { var s = new EditorState(); s.CreateNode(new Vector2(40, 60)); Check(s.Creature.Nodes.Count == 1); });
Run("next node adds connection and selects child", () => { var s = new EditorState(); var root = s.CreateNode(Vector2.Zero); var child = s.AddNextNode(); Check(child is not null && s.Creature.Nodes.Count == 2 && s.Creature.Connections.Count == 1 && s.SelectedNode == child && s.Creature.Connections[0].ParentNodeId == root.Id); });
Run("spacing is center to center regardless of radius", () => { var s = new EditorState(); var root = s.CreateNode(Vector2.Zero); root.Radius = 10; var child = s.AddNextNode()!; child.Radius = 100; Check(Math.Abs(Vector2.Distance(root.Position, child.Position) - s.Creature.ChainSettings.Spacing) < 0.001f); });
Run("rotation zero points right", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero).Rotation = 0; var child = s.AddNextNode()!; Check(Vector2.Distance(child.Position, new Vector2(50, 0)) < 0.001f); });
Run("rotation ninety points down", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero).Rotation = 90; var child = s.AddNextNode()!; Check(Vector2.Distance(child.Position, new Vector2(0, 50)) < 0.001f); });
Run("repeated creation is ordered", () => { var s = new EditorState(); var root = s.CreateNode(Vector2.Zero); var first = s.AddNextNode()!; var second = s.AddNextNode()!; Check(s.Creature.Nodes[0] == root && s.Creature.Nodes[1] == first && s.Creature.Nodes[2] == second && s.Creature.Connections.Count == 2); });
Run("node indices are list order", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.AddNextNode(); Check(s.Creature.Nodes.Select((node, index) => s.Creature.Nodes.IndexOf(node) == index).All(x => x)); });
Run("spacing rebuild updates all rest lengths", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.AddNextNode(); s.SetSpacing(80); Check(s.Creature.Connections.All(c => c.RestLength == 80) && s.Creature.Nodes.Zip(s.Creature.Nodes.Skip(1)).All(pair => Math.Abs(Vector2.Distance(pair.First.Position, pair.Second.Position) - 80) < 0.001f)); });
Run("spacing rebuild preserves directions", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode()!.Rotation = 45; s.AddNextNode(); var before = Vector2.Normalize(s.Creature.Nodes[2].Position - s.Creature.Nodes[1].Position); s.SetSpacing(100); var after = Vector2.Normalize(s.Creature.Nodes[2].Position - s.Creature.Nodes[1].Position); Check(Vector2.Distance(before, after) < 0.001f); });
Run("end deletion removes connection", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.DeleteSelected(); Check(s.Creature.Nodes.Count == 1 && s.Creature.Connections.Count == 0); });
Run("middle deletion removes descendants", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); var middle = s.AddNextNode()!; s.AddNextNode(); s.Select(middle); s.DeleteSelected(); Check(s.Creature.Nodes.Count == 1 && s.Creature.Connections.Count == 0); });
Run("mode switching preserves chain", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.SetMode(EditorMode.Play); s.SetMode(EditorMode.Create); Check(s.Creature.Nodes.Count == 2 && s.Creature.Connections.Count == 1); });
Run("reset removes nodes and connections", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.Reset(); Check(s.Creature.Nodes.Count == 0 && s.Creature.Connections.Count == 0); });
Run("direction helper normalizes construction", () => { var result = ChainMath.GetPositionAtSpacing(Vector2.Zero, new Vector2(3, 4), 10); Check(Vector2.Distance(result, new Vector2(6, 8)) < 0.001f); });
Run("constrain helper ignores candidate distance", () => { var result = ChainMath.ConstrainToSpacing(Vector2.Zero, new Vector2(100, 0), 50, Vector2.UnitY); Check(Vector2.Distance(result, new Vector2(50, 0)) < 0.001f); });
Run("default ramp exists", () => { var ramp = new CreatureConstructionLab.Model.BodySizeRamp(); Check(ramp.Points.Count == 2 && ramp.Points[0].Position == 0 && ramp.Points[^1].Position == 1); });
Run("ramp endpoints sample expected values", () => { var ramp = new CreatureConstructionLab.Model.BodySizeRamp(); Check(Math.Abs(ramp.Sample(0) - 1) < 0.001f && Math.Abs(ramp.Sample(1) - 0.4f) < 0.001f); });
Run("ramp linearly interpolates and clamps", () => { var ramp = new CreatureConstructionLab.Model.BodySizeRamp(); Check(Math.Abs(ramp.Sample(0.5f) - 0.7f) < 0.001f && Math.Abs(ramp.Sample(-1) - 1) < 0.001f && Math.Abs(ramp.Sample(2) - 0.4f) < 0.001f); });
Run("node radii derive from normalized positions", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.AddNextNode(); Check(s.Creature.Nodes[0].NormalizedPosition == 0 && Math.Abs(s.Creature.Nodes[1].NormalizedPosition - 0.5f) < 0.001f && s.Creature.Nodes[0].Radius > s.Creature.Nodes[2].Radius); });
Run("adding node resamples existing radii", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); var before = s.Creature.Nodes[1].Radius; s.AddNextNode(); Check(Math.Abs(s.Creature.Nodes[1].NormalizedPosition - 0.5f) < 0.001f && s.Creature.Nodes[1].Radius > before); });
Run("adding and deleting ramp points preserves endpoints", () => { var s = new EditorState(); var point = s.AddRampPoint(0.5f, 1.5f)!; Check(s.Creature.BodySizeRamp.Points.Count == 3 && s.RemoveRampPoint(point) && s.Creature.BodySizeRamp.Points.Count == 2 && !s.RemoveRampPoint(s.Creature.BodySizeRamp.Points[0])); });
Run("ramp point positions stay ordered", () => { var s = new EditorState(); s.AddRampPoint(0.8f, 1); s.AddRampPoint(0.2f, 1); Check(s.Creature.BodySizeRamp.Points.SequenceEqual(s.Creature.BodySizeRamp.Points.OrderBy(p => p.Position))); });
Run("spacing does not change ramp", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); var sample = s.Creature.BodySizeRamp.Sample(0.5f); s.SetSpacing(90); Check(s.Creature.BodySizeRamp.Sample(0.5f) == sample); });
Run("mode switching preserves ramp", () => { var s = new EditorState(); s.AddRampPoint(0.5f, 1.6f); s.SetMode(EditorMode.Play); s.SetMode(EditorMode.Create); Check(s.Creature.BodySizeRamp.Points.Count == 3 && s.Creature.BodySizeRamp.Sample(0.5f) == 1.6f); });
Run("reset restores default ramp", () => { var s = new EditorState(); s.AddRampPoint(0.5f, 1.6f); s.CreateNode(Vector2.Zero); s.Reset(); Check(s.Creature.Nodes.Count == 0 && s.Creature.BodySizeRamp.Points.Count == 2 && Math.Abs(s.Creature.BodySizeRamp.Sample(0.5f) - 0.7f) < 0.001f); });
Console.WriteLine($"{passed} editor tests passed.");

void Run(string name, Action test) { test(); passed++; Console.WriteLine($"PASS {name}"); }
void Check(bool condition) { if (!condition) throw new InvalidOperationException("assertion failed"); }
