using System.Numerics;
using CreatureConstructionLab.Editor;
using CreatureConstructionLab.Model;
using CreatureConstructionLab.Simulation;
using CreatureConstructionLab.IO;
using CreatureConstructionLab.Rendering;

var passed = 0;
Run("starts empty", () => { var s = new EditorState(); Check(s.Creature.Nodes.Count == 0 && s.Creature.Connections.Count == 0); });
Run("first node can be created", () => { var s = new EditorState(); s.CreateNode(new Vector2(40, 60)); Check(s.Creature.Nodes.Count == 1); });
Run("next node adds connection and selects child", () => { var s = new EditorState(); var root = s.CreateNode(Vector2.Zero); var child = s.AddNextNode(); Check(child is not null && s.Creature.Nodes.Count == 2 && s.Creature.Connections.Count == 1 && s.SelectedNode == child && s.Creature.Connections[0].ParentNodeId == root.Id); });
Run("spacing is center to center regardless of radius", () => { var s = new EditorState(); var root = s.CreateNode(Vector2.Zero); root.Radius = 10; var child = s.AddNextNode()!; child.Radius = 100; Check(Math.Abs(Vector2.Distance(root.Position, child.Position) - s.Creature.ChainSettings.Spacing) < 0.001f); });
Run("rotation zero points right", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero).Rotation = 0; var child = s.AddNextNode()!; Check(Vector2.Distance(child.Position, new Vector2(50, 0)) < 0.001f); });
Run("rotation ninety points down", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero).Rotation = 90; var child = s.AddNextNode()!; Check(Vector2.Distance(child.Position, new Vector2(0, 50)) < 0.001f); });
Run("repeated creation is ordered", () => { var s = new EditorState(); var root = s.CreateNode(Vector2.Zero); var first = s.AddNextNode()!; var second = s.AddNextNode()!; Check(s.Creature.Nodes[0] == root && s.Creature.Nodes[1] == first && s.Creature.Nodes[2] == second && s.Creature.Connections.Count == 2); });
Run("node indices are list order", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.AddNextNode(); Check(s.Creature.Nodes.Select((node, index) => s.Creature.Nodes.IndexOf(node) == index).All(x => x)); });
Run("spacing rebuild updates all rest lengths", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.AddNextNode(); s.SetSpacing(80); Check(s.Creature.Connections.All(c => c.RestLength == 80) && s.Creature.Nodes.Zip(s.Creature.Nodes.Skip(1)).All(pair => Math.Abs(Vector2.Distance(pair.First.Position, pair.Second.Position) - 80) < 0.001f)); });
Run("spacing rebuild preserves directions", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode()!.Rotation = 45; s.AddNextNode(); var before = Vector2.Normalize(s.Creature.Nodes[2].Position - s.Creature.Nodes[1].Position); s.SetSpacing(100); var after = Vector2.Normalize(s.Creature.Nodes[2].Position - s.Creature.Nodes[1].Position); Check(Vector2.Distance(before, after) < 0.001f); });
Run("end deletion removes connection", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.DeleteSelected(); Check(s.Creature.Nodes.Count == 1 && s.Creature.Connections.Count == 0); });
Run("middle deletion removes descendants", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); var middle = s.AddNextNode()!; s.AddNextNode(); s.Select(middle); s.DeleteSelected(); Check(s.Creature.Nodes.Count == 1 && s.Creature.Connections.Count == 0); });
Run("mode switching preserves chain", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.SetMode(EditorMode.Play); s.SetMode(EditorMode.Create); Check(s.Creature.Nodes.Count == 2 && s.Creature.Connections.Count == 1); });
Run("reset removes nodes and connections", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.Reset(); Check(s.Creature.Nodes.Count == 0 && s.Creature.Connections.Count == 0); });
Run("direction helper normalizes construction", () => { var result = ChainMath.GetPositionAtSpacing(Vector2.Zero, new Vector2(3, 4), 10); Check(Vector2.Distance(result, new Vector2(6, 8)) < 0.001f); });
Run("constrain helper ignores candidate distance", () => { var result = ChainMath.ConstrainToSpacing(Vector2.Zero, new Vector2(100, 0), 50, Vector2.UnitY); Check(Vector2.Distance(result, new Vector2(50, 0)) < 0.001f); });
Run("default ramp exists", () => { var ramp = new CreatureConstructionLab.Model.BodySizeRamp(); Check(ramp.Points.Count == 2 && ramp.Points[0].Position == 0 && ramp.Points[^1].Position == 1); });
Run("ramp endpoints sample expected values", () => { var ramp = new CreatureConstructionLab.Model.BodySizeRamp(); Check(Math.Abs(ramp.Sample(0) - 1) < 0.001f && Math.Abs(ramp.Sample(1) - 0.4f) < 0.001f); });
Run("ramp linearly interpolates and clamps", () => { var ramp = new CreatureConstructionLab.Model.BodySizeRamp(); Check(Math.Abs(ramp.Sample(0.5f) - 0.7f) < 0.001f && Math.Abs(ramp.Sample(-1) - 1) < 0.001f && Math.Abs(ramp.Sample(2) - 0.4f) < 0.001f); });
Run("node radii derive from normalized positions", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.AddNextNode(); Check(s.Creature.Nodes[0].NormalizedPosition == 0 && Math.Abs(s.Creature.Nodes[1].NormalizedPosition - 0.5f) < 0.001f && s.Creature.Nodes[0].Radius > s.Creature.Nodes[2].Radius); });
Run("adding node resamples existing radii", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); var before = s.Creature.Nodes[1].Radius; s.AddNextNode(); Check(Math.Abs(s.Creature.Nodes[1].NormalizedPosition - 0.5f) < 0.001f && s.Creature.Nodes[1].Radius > before); });
Run("adding and deleting ramp points preserves endpoints", () => { var s = new EditorState(); var point = s.AddRampPoint(0.5f, 1.5f)!; Check(s.Creature.BodySizeRamp.Points.Count == 3 && s.RemoveRampPoint(point) && s.Creature.BodySizeRamp.Points.Count == 2 && !s.RemoveRampPoint(s.Creature.BodySizeRamp.Points[0])); });
Run("ramp point positions stay ordered", () => { var s = new EditorState(); s.AddRampPoint(0.8f, 1); s.AddRampPoint(0.2f, 1); Check(s.Creature.BodySizeRamp.Points.SequenceEqual(s.Creature.BodySizeRamp.Points.OrderBy(p => p.Position))); });
Run("spacing does not change ramp", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); var sample = s.Creature.BodySizeRamp.Sample(0.5f); s.SetSpacing(90); Check(s.Creature.BodySizeRamp.Sample(0.5f) == sample); });
Run("mode switching preserves ramp", () => { var s = new EditorState(); s.AddRampPoint(0.5f, 1.6f); s.SetMode(EditorMode.Play); s.SetMode(EditorMode.Create); Check(s.Creature.BodySizeRamp.Points.Count == 3 && s.Creature.BodySizeRamp.Sample(0.5f) == 1.6f); });
Run("reset restores default ramp", () => { var s = new EditorState(); s.AddRampPoint(0.5f, 1.6f); s.CreateNode(Vector2.Zero); s.Reset(); Check(s.Creature.Nodes.Count == 0 && s.Creature.BodySizeRamp.Points.Count == 2 && Math.Abs(s.Creature.BodySizeRamp.Sample(0.5f) - 0.7f) < 0.001f); });
Run("zero-node play state is safe", () => { var simulator = new CreatureSimulator(); var creature = new CreatureDefinition(); simulator.SetTarget(new Vector2(100, 100)); simulator.Update(creature, 1); Check(simulator.State.Positions.Count == 0); });
Run("root follows without teleporting", () => { var creature = new CreatureDefinition(); creature.Nodes.Add(new CreatureNode { Position = Vector2.Zero }); var simulator = new CreatureSimulator(); simulator.Reset(creature); simulator.SetTarget(new Vector2(100, 0)); simulator.Update(creature, 1f / 60); Check(simulator.State.Positions[0].X > 0 && simulator.State.Positions[0].X < 100); });
Run("root speed is capped", () => { var creature = new CreatureDefinition(); creature.Nodes.Add(new CreatureNode { Position = Vector2.Zero }); var simulator = new CreatureSimulator(); simulator.State.MaxSpeed = 20; simulator.Reset(creature); simulator.SetTarget(new Vector2(1000, 0)); for (var i = 0; i < 30; i++) simulator.Update(creature, 1f / 60); Check(simulator.State.Velocities[0].Length() <= 20.001f); });
Run("root acceleration is limited", () => { var creature = new CreatureDefinition(); creature.Nodes.Add(new CreatureNode { Position = Vector2.Zero }); var simulator = new CreatureSimulator(); simulator.State.AccelerationStrength = 30; simulator.Reset(creature); simulator.SetTarget(new Vector2(1000, 0)); simulator.Update(creature, 1f / 60); Check(simulator.State.Velocities[0].Length() < 1); });
Run("damping reduces velocity", () => { var creature = new CreatureDefinition(); creature.Nodes.Add(new CreatureNode { Position = Vector2.Zero }); var simulator = new CreatureSimulator(); simulator.Reset(creature); simulator.State.SetTarget(Vector2.Zero); simulator.State.Velocities[0] = new Vector2(50, 0); simulator.State.Damping = 10; simulator.Update(creature, 1f / 60); Check(simulator.State.Velocities[0].Length() < 50); });
Run("body follows at rest spacing", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.AddNextNode(); s.SetMode(EditorMode.Play); s.SetPlayTarget(new Vector2(400, 0)); for (var i = 0; i < 60; i++) s.UpdateSimulation(1f / 60); Check(s.Simulator.State.Positions.Zip(s.Simulator.State.Positions.Skip(1)).All(pair => Math.Abs(Vector2.Distance(pair.First, pair.Second) - s.Creature.ChainSettings.Spacing) < 0.2f)); });
Run("pause stops and resume continues", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.SetMode(EditorMode.Play); s.SetPlayTarget(new Vector2(300, 0)); s.SetPaused(true); s.UpdateSimulation(1); var paused = s.Simulator.State.Positions[0]; s.SetPaused(false); s.UpdateSimulation(0.1f); Check(s.Simulator.State.Positions[0] != paused && s.Simulator.State.Velocities[0].X > 0); });
Run("reset simulation restores definition and clears velocity", () => { var s = new EditorState(); var root = s.CreateNode(new Vector2(20, 30)); s.SetMode(EditorMode.Play); s.SetPlayTarget(new Vector2(300, 300)); s.UpdateSimulation(1); s.ResetSimulation(); Check(s.Simulator.State.Positions[0] == root.Position && s.Simulator.State.Velocities[0] == Vector2.Zero); });
Run("play to create preserves constructed positions", () => { var s = new EditorState(); var root = s.CreateNode(new Vector2(20, 30)); s.AddNextNode(); var original = s.Creature.Nodes.Select(n => n.Position).ToArray(); s.SetMode(EditorMode.Play); s.SetPlayTarget(new Vector2(400, 400)); s.UpdateSimulation(1); s.SetMode(EditorMode.Create); Check(s.Creature.Nodes.Select(n => n.Position).SequenceEqual(original) && root.Position == new Vector2(20, 30)); });
Run("simulation speed affects progression", () => { var creature = new CreatureDefinition(); creature.Nodes.Add(new CreatureNode { Position = Vector2.Zero }); var slow = new CreatureSimulator(); var fast = new CreatureSimulator(); slow.State.SimulationSpeed = 0.5f; fast.State.SimulationSpeed = 2; slow.Reset(creature); fast.Reset(creature); slow.SetTarget(new Vector2(300, 0)); fast.SetTarget(new Vector2(300, 0)); slow.Update(creature, 0.1f); fast.Update(creature, 0.1f); Check(fast.State.SimulationTime > slow.State.SimulationTime); });
Run("simulation remains finite", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); for (var i = 0; i < 20; i++) s.AddNextNode(); s.SetMode(EditorMode.Play); s.SetPlayTarget(new Vector2(10000, -10000)); for (var i = 0; i < 600; i++) s.UpdateSimulation(1f / 60); Check(s.Simulator.State.Positions.All(p => float.IsFinite(p.X) && float.IsFinite(p.Y))); });
Run("disabled wave produces zero offset", () => { var settings = new WaveMotionSettings { Enabled = false }; Check(BodyWaveGenerator.CalculateOffset(1, 0.8f, Vector2.UnitY, settings, 50) == Vector2.Zero); });
Run("wave changes with time", () => { var settings = new WaveMotionSettings { Enabled = true }; var a = BodyWaveGenerator.CalculateOffset(0, 0.8f, Vector2.UnitY, settings, 50); var b = BodyWaveGenerator.CalculateOffset(0.25f, 0.8f, Vector2.UnitY, settings, 50); Check(a != b); });
Run("wave phase differs along chain", () => { var settings = new WaveMotionSettings { Enabled = true }; var head = BodyWaveGenerator.CalculateOffset(0.2f, 0.25f, Vector2.UnitX, settings, 50); var tail = BodyWaveGenerator.CalculateOffset(0.2f, 0.9f, Vector2.UnitX, settings, 50); Check(head != tail); });
Run("root wave influence is zero", () => { var settings = new WaveMotionSettings { Enabled = true }; Check(BodyWaveGenerator.CalculateOffset(1, 0, Vector2.UnitY, settings, 50) == Vector2.Zero); });
Run("tail receives stronger influence", () => { var settings = new WaveMotionSettings { Enabled = true, Phase = 0 }; var head = BodyWaveGenerator.CalculateOffset(0.1f, 0.25f, Vector2.UnitY, settings, 50).Length(); var tail = BodyWaveGenerator.CalculateOffset(0.1f, 1, Vector2.UnitY, settings, 50).Length(); Check(tail > head); });
Run("amplitude controls wave magnitude", () => { var small = new WaveMotionSettings { Enabled = true, Amplitude = 2, Phase = 0 }; var large = new WaveMotionSettings { Enabled = true, Amplitude = 12, Phase = 0 }; Check(BodyWaveGenerator.CalculateOffset(0.2f, 0.75f, Vector2.UnitY, large, 50).Length() > BodyWaveGenerator.CalculateOffset(0.2f, 0.75f, Vector2.UnitY, small, 50).Length()); });
Run("influence zero disables wave", () => { var settings = new WaveMotionSettings { Enabled = true, Influence = 0 }; Check(BodyWaveGenerator.CalculateOffset(0.5f, 0.8f, Vector2.UnitY, settings, 50) == Vector2.Zero); });
Run("paused simulation does not advance wave time", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.SetMode(EditorMode.Play); s.SetPaused(true); s.UpdateSimulation(1); Check(s.Simulator.State.SimulationTime == 0); });
Run("resume advances wave time", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.SetMode(EditorMode.Play); s.UpdateSimulation(0.1f); Check(s.Simulator.State.SimulationTime > 0); });
Run("reset restores wave time", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.SetMode(EditorMode.Play); s.UpdateSimulation(0.1f); s.ResetSimulation(); Check(s.Simulator.State.SimulationTime == 0 && !s.Simulator.State.Wave.Enabled); });
Run("wave preserves connection lengths", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); for (var i = 0; i < 8; i++) s.AddNextNode(); s.SetMode(EditorMode.Play); s.UpdateSimulation(1); Check(s.Simulator.State.Positions.Zip(s.Simulator.State.Positions.Skip(1)).All(pair => Math.Abs(Vector2.Distance(pair.First, pair.Second) - s.Creature.ChainSettings.Spacing) < 0.01f)); });
Run("single and two node waves are safe", () => { var one = new EditorState(); one.CreateNode(Vector2.Zero); one.SetMode(EditorMode.Play); one.UpdateSimulation(1); var two = new EditorState(); two.CreateNode(Vector2.Zero); two.AddNextNode(); two.SetMode(EditorMode.Play); two.UpdateSimulation(1); Check(one.Simulator.State.Positions.Count == 1 && two.Simulator.State.Positions.Count == 2); });
Run("wave play to create restores construction", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.AddNextNode(); var original = s.Creature.Nodes.Select(n => n.Position).ToArray(); s.SetMode(EditorMode.Play); s.UpdateSimulation(1); s.SetMode(EditorMode.Create); Check(s.Creature.Nodes.Select(n => n.Position).SequenceEqual(original)); });
Run("save serializes authored definition", () => { var s = new EditorState(); s.CreateNode(new Vector2(10, 20)); s.AddNextNode(); s.AddRampPoint(0.5f, 1.4f); var path = TempPath(); CreatureFileService.Save(path, s.Creature); var json = File.ReadAllText(path); File.Delete(path); Check(json.Contains("Connections") && json.Contains("RampPoints") && json.Contains("PositionX")); });
Run("save load round trip restores definition", () => { var s = new EditorState(); s.CreateNode(new Vector2(10, 20)).Rotation = 15; s.AddNextNode(); s.SetSpacing(70); s.SetBaseRadius(30); s.AddRampPoint(0.5f, 1.4f); var path = TempPath(); CreatureFileService.Save(path, s.Creature); Check(CreatureFileService.TryLoad(path, out var loaded, out _) && loaded is not null); File.Delete(path); Check(loaded!.Nodes.Count == 2 && loaded.Connections.Count == 1 && loaded.ChainSettings.Spacing == 70 && loaded.BaseRadius == 30 && loaded.BodySizeRamp.Points.Count == 3 && loaded.Nodes[0].Rotation == 15); });
Run("load derives radii from ramp", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); var path = TempPath(); CreatureFileService.Save(path, s.Creature); CreatureFileService.TryLoad(path, out var loaded, out _); File.Delete(path); var restored = new EditorState(); restored.LoadDefinition(loaded!); var expected = restored.Creature.BaseRadius * restored.Creature.BodySizeRamp.Sample(1); Check(Math.Abs(restored.Creature.Nodes[1].Radius - expected) < 0.001f); });
Run("save during play preserves authored positions", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); var original = s.Creature.Nodes.Select(n => n.Position).ToArray(); s.SetMode(EditorMode.Play); s.SetPlayTarget(new Vector2(500, 500)); s.UpdateSimulation(1); var path = TempPath(); CreatureFileService.Save(path, s.Creature); CreatureFileService.TryLoad(path, out var loaded, out _); File.Delete(path); Check(loaded!.Nodes.Select(n => n.Position).SequenceEqual(original)); });
Run("invalid JSON is rejected safely", () => { var path = TempPath(); File.WriteAllText(path, "not json"); var result = CreatureFileService.TryLoad(path, out _, out var error); File.Delete(path); Check(!result && error.Length > 0); });
Run("invalid connection references are rejected", () => { var path = TempPath(); File.WriteAllText(path, "{\"Nodes\":[],\"Connections\":[{\"ParentNodeId\":\"bad\",\"ChildNodeId\":\"bad\",\"RestLength\":1,\"Stiffness\":1,\"Damping\":0}],\"Chain\":{\"Spacing\":50,\"Stiffness\":1,\"Damping\":0.1},\"Body\":{\"BaseRadius\":24,\"RampPoints\":[{\"Position\":0,\"Value\":1},{\"Position\":1,\"Value\":0.4}]}}"); var result = CreatureFileService.TryLoad(path, out _, out _); File.Delete(path); Check(!result); });
Run("editor load enters create and clears play state", () => { var source = new EditorState(); source.CreateNode(new Vector2(4, 5)); var path = TempPath(); CreatureFileService.Save(path, source.Creature); var target = new EditorState(); target.CreateNode(Vector2.Zero); target.SetMode(EditorMode.Play); CreatureFileService.TryLoad(path, out var loaded, out _); target.LoadDefinition(loaded!); File.Delete(path); Check(target.Mode == EditorMode.Create && target.Creature.Nodes[0].Position == new Vector2(4, 5) && target.Simulator.State.Positions[0] == new Vector2(4, 5)); });
Run("final default tuning is gentler and faster", () => { var s = new EditorState(); Check(Math.Abs(s.Simulator.State.Wave.Amplitude - 4) < 0.001f && Math.Abs(s.Simulator.State.MaxSpeed - 720) < 0.001f && !s.Simulator.State.Wave.Enabled); });
Run("wave amplitude can still increase", () => { var s = new EditorState(); s.SetWaveSettings(true, 20, 1.2f, 2.8f, 1); Check(s.Simulator.State.Wave.Amplitude > 4); });
Run("child turn reference spans 270 degrees", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); var child = s.AddNextNode()!; s.Select(child); s.SetSelectedRotation(135); Check(Math.Abs(ChainMath.NormalizeDegrees(child.Rotation - 0) - 135) < 0.001f); s.SetSelectedRotation(-135); Check(Math.Abs(ChainMath.NormalizeDegrees(child.Rotation) + 135) < 0.001f); });
Run("backward child rotation clamps to boundary", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); var child = s.AddNextNode()!; s.Select(child); s.SetSelectedRotation(180); Check(Math.Abs(child.Rotation - 135) < 0.001f); var next = s.AddNextNode()!; Check(Math.Abs(Vector2.Distance(child.Position, next.Position) - s.Creature.ChainSettings.Spacing) < 0.001f); });
Run("root turning remains unrestricted", () => { var s = new EditorState(); var root = s.CreateNode(Vector2.Zero); s.SetSelectedRotation(180); Check(Math.Abs(root.Rotation - 180) < 0.001f); });
Run("smooth interpolation passes through points", () => { var s = new EditorState(); s.SetRampInterpolation(RampInterpolationMode.Smooth); s.AddRampPoint(0.5f, 0.2f); Check(Math.Abs(s.Creature.BodySizeRamp.Sample(0.5f) - 0.2f) < 0.001f); });
Run("smooth interpolation is non-linear", () => { var ramp = new BodySizeRamp(); ramp.AddPoint(0.5f, 0.2f); ramp.Interpolation = RampInterpolationMode.Smooth; Check(Math.Abs(ramp.Sample(0.125f) - 0.8f) > 0.01f); });
Run("bezier interpolation samples safely", () => { var ramp = new BodySizeRamp(); ramp.AddPoint(0.35f, 1.8f); ramp.AddPoint(0.7f, 0.2f); ramp.Interpolation = RampInterpolationMode.Bezier; var sample = ramp.Sample(0.5f); Check(float.IsFinite(sample) && sample >= BodySizeRamp.MinValue && sample <= BodySizeRamp.MaxValue); });
Run("many ramp points remain ordered", () => { var s = new EditorState(); for (var i = 1; i <= 20; i++) s.AddRampPoint(i / 21f, 0.3f + i / 30f); Check(s.Creature.BodySizeRamp.Points.Count == 22 && s.Creature.BodySizeRamp.Points.First().Position == 0 && s.Creature.BodySizeRamp.Points.Last().Position == 1 && s.Creature.BodySizeRamp.Points.Zip(s.Creature.BodySizeRamp.Points.Skip(1)).All(pair => pair.First.Position < pair.Second.Position)); });
Run("interpolation survives save load", () => { var s = new EditorState(); s.SetRampInterpolation(RampInterpolationMode.Bezier); s.AddRampPoint(0.5f, 1.5f); var path = TempPath(); CreatureFileService.Save(path, s.Creature); CreatureFileService.TryLoad(path, out var loaded, out _); File.Delete(path); Check(loaded!.BodySizeRamp.Interpolation == RampInterpolationMode.Bezier && loaded.BodySizeRamp.Points.Count == 3); });
Run("older files default interpolation to linear", () => { var path = TempPath(); File.WriteAllText(path, "{\"Nodes\":[],\"Connections\":[],\"Chain\":{\"Spacing\":50,\"Stiffness\":1,\"Damping\":0.1},\"Body\":{\"BaseRadius\":24,\"RampPoints\":[{\"Position\":0,\"Value\":1},{\"Position\":1,\"Value\":0.4}]}}"); var result = CreatureFileService.TryLoad(path, out var loaded, out _); File.Delete(path); Check(result && loaded!.BodySizeRamp.Interpolation == RampInterpolationMode.Linear); });
Run("skin samples radius-offset points smoothly", () => { var geometry = CreatureSkinGeometry.Build(new[] { Vector2.Zero, new Vector2(50, 0), new Vector2(100, 0) }, new[] { 10f, 20f, 5f }); Check(geometry.Left.Length == 17 && geometry.Radii.Length == 17 && Math.Abs(Vector2.Distance(geometry.Left[8], new Vector2(50, 0)) - 20) < 0.001f && Math.Abs(Vector2.Distance(geometry.Right[^1], new Vector2(100, 0)) - 5) < 0.001f); });
Run("straight smoothed skin stays straight", () => { var geometry = CreatureSkinGeometry.Build(new[] { Vector2.Zero, new Vector2(50, 0), new Vector2(100, 0), new Vector2(150, 0) }, new[] { 10f, 10f, 10f, 10f }); Check(geometry.Left.All(p => Math.Abs(p.Y - 10) < 0.001f)); });
Run("skin handles one and two nodes", () => { var one = CreatureSkinGeometry.Build(new[] { Vector2.Zero }, new[] { 10f }); var two = CreatureSkinGeometry.Build(new[] { Vector2.Zero, new Vector2(50, 0) }, new[] { 10f, 5f }); Check(one.Outline.Length >= 16 && two.Right.Length == 9 && two.Outline.Length > 20); });
Run("skin remains finite on curved chain", () => { var geometry = CreatureSkinGeometry.Build(new[] { Vector2.Zero, new Vector2(40, 0), new Vector2(60, 30), new Vector2(90, 50) }, new[] { 10f, 20f, 15f, 4f }); Check(geometry.Left.Concat(geometry.Right).All(p => float.IsFinite(p.X) && float.IsFinite(p.Y))); });
Run("terminal caps fully represent endpoint radii", () => { var geometry = CreatureSkinGeometry.Build(new[] { Vector2.Zero, new Vector2(50, 0), new Vector2(100, 0) }, new[] { 10f, 20f, 5f }); Check(geometry.HeadCap.Any(p => p.X <= -9.9f) && geometry.TailCap.Any(p => p.X >= 104.9f) && geometry.Outline.All(p => float.IsFinite(p.X) && float.IsFinite(p.Y))); });
Run("left-facing tail cap bulges away from body", () => { var geometry = CreatureSkinGeometry.Build(new[] { new Vector2(100, 300), new Vector2(50, 300), new Vector2(0, 300) }, new[] { 8f, 12f, 10f }); Check(geometry.TailCap.Any(p => p.X <= -9.9f) && geometry.TailCap.Any(p => p.X > -0.1f && p.X < 0.1f)); });
Run("cap midpoints point outward", () => { var positions = new[] { Vector2.Zero, new Vector2(50, 0), new Vector2(100, 0) }; var geometry = CreatureSkinGeometry.Build(positions, new[] { 10f, 20f, 5f }); var headMid = geometry.HeadCap[CreatureSkinGeometry.CapSamples / 2]; var tailMid = geometry.TailCap[CreatureSkinGeometry.CapSamples / 2]; Check(Math.Abs(Vector2.Dot(headMid - positions[0], -Vector2.UnitX) - 10) < 0.001f && Math.Abs(Vector2.Dot(tailMid - positions[^1], Vector2.UnitX) - 5) < 0.001f); });
Run("terminal caps stay valid on tight curve", () => { var geometry = CreatureSkinGeometry.Build(new[] { Vector2.Zero, new Vector2(30, 0), new Vector2(35, 25), new Vector2(10, 45) }, new[] { 18f, 12f, 9f, 4f }); Check(geometry.Outline.Length > 0 && geometry.Outline.All(p => float.IsFinite(p.X) && float.IsFinite(p.Y))); });
Run("body ramp still controls terminal cap radius", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.SetBaseRadius(30); var geometry = CreatureSkinGeometry.Build(s.Creature.Nodes.Select(n => n.Position).ToArray(), s.Creature.Nodes.Select(n => n.Radius).ToArray()); Check(geometry.HeadCap.Any(p => p.X <= -s.Creature.Nodes[0].Radius + 0.1f)); });
Run("skin does not alter chain definition", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); var before = s.Creature.Nodes.Select(n => n.Position).ToArray(); _ = CreatureSkinGeometry.Build(s.Creature.Nodes.Select(n => n.Position).ToArray(), s.Creature.Nodes.Select(n => n.Radius).ToArray()); Check(s.Creature.Nodes.Select(n => n.Position).SequenceEqual(before)); });
Run("feature can be added and mirrored", () => { var s = new EditorState(); var head = s.CreateNode(Vector2.Zero); var feature = s.AddFeature(); feature.LocalPosition = new Vector2(20, 8); Check(feature.Id != Guid.Empty && feature.ParentNodeId == head.Id && feature.Mirrored); var primary = CreatureFeatureTransform.ToWorld(feature, Vector2.Zero, Vector2.UnitX, false); var mirror = CreatureFeatureTransform.ToWorld(feature, Vector2.Zero, Vector2.UnitX, true); Check(primary.Position.Y == -mirror.Position.Y && primary.Position.X == mirror.Position.X); });
Run("feature transform follows and rotates parent", () => { var feature = new CreatureFeature { LocalPosition = new Vector2(10, 5), Scale = 2 }; var a = CreatureFeatureTransform.ToWorld(feature, Vector2.Zero, Vector2.UnitX, false); var b = CreatureFeatureTransform.ToWorld(feature, new Vector2(30, 40), Vector2.UnitY, false); Check(b.Position == new Vector2(25, 50) && b.Scale == 2 && a.Position == new Vector2(10, 5)); });
Run("forked tongue defaults to root and is singular", () => { var s = new EditorState(); var head = s.CreateNode(Vector2.Zero); var tongue = s.AddFeature(CreatureFeatureType.ForkedTongue); Check(tongue.ParentNodeId == head.Id && tongue.Type == CreatureFeatureType.ForkedTongue && !tongue.Mirrored && !tongue.SupportsMirroring); });
Run("forked tongue geometry is symmetric and parameterized", () => { var tongue = new CreatureFeature { Type = CreatureFeatureType.ForkedTongue, TongueLength = 30, TongueForkLength = 10, TongueForkAngle = 30 }; var geometry = ForkedTongueGeometry.Build(tongue, new FeatureWorldTransform(Vector2.Zero, 0, 1), 5); Check(Math.Abs(geometry.Junction.X - 35) < 0.001f && Math.Abs(geometry.UpperTip.Y + geometry.LowerTip.Y) < 0.001f && Math.Abs(Vector2.Distance(geometry.Junction, geometry.UpperTip) - 10) < 0.001f); });
Run("forked tongue follows parent transform", () => { var tongue = new CreatureFeature { Type = CreatureFeatureType.ForkedTongue }; var a = ForkedTongueGeometry.Build(tongue, new FeatureWorldTransform(Vector2.Zero, 0, 1), 5); var b = ForkedTongueGeometry.Build(tongue, new FeatureWorldTransform(new Vector2(20, 30), 90, 1), 5); Check(b.Start == new Vector2(20, 35) && a.Start == new Vector2(5, 0)); });
Run("feature save load and old eye migration", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); var feature = s.AddFeature(); feature.LocalPosition = new Vector2(18, 7); feature.EyeSize = 8; var path = TempPath(); CreatureFileService.Save(path, s.Creature); Check(CreatureFileService.TryLoad(path, out var loaded, out _) && loaded!.Features.Count == 1 && loaded.Features[0].LocalPosition == new Vector2(18, 7)); File.Delete(path); var old = TempPath(); File.WriteAllText(old, "{\"Nodes\":[{\"Id\":\"" + Guid.NewGuid() + "\",\"PositionX\":0,\"PositionY\":0,\"Rotation\":0}],\"Connections\":[],\"Chain\":{\"Spacing\":50,\"Stiffness\":1,\"Damping\":0.1},\"Body\":{\"BaseRadius\":24,\"RampPoints\":[{\"Position\":0,\"Value\":1},{\"Position\":1,\"Value\":0.4}]},\"Eyes\":{\"Enabled\":true,\"Size\":6,\"Spacing\":20,\"ForwardOffset\":15}}"); Check(CreatureFileService.TryLoad(old, out var migrated, out _) && migrated!.Features.Count == 1 && migrated.Features[0].EyeSize == 6); File.Delete(old); });
Run("forked tongue settings survive save load", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); var tongue = s.AddFeature(CreatureFeatureType.ForkedTongue); tongue.TongueLength = 44; tongue.TongueForkLength = 16; tongue.TongueForkAngle = 42; var path = TempPath(); CreatureFileService.Save(path, s.Creature); Check(CreatureFileService.TryLoad(path, out var loaded, out _) && loaded!.Features.Count == 1 && loaded.Features[0].Type == CreatureFeatureType.ForkedTongue && loaded.Features[0].TongueLength == 44 && loaded.Features[0].TongueForkAngle == 42 && !loaded.Features[0].Mirrored); File.Delete(path); });
Run("tongue does not modify simulation state", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); var before = s.Simulator.State.Positions.ToArray(); s.AddFeature(CreatureFeatureType.ForkedTongue); Check(s.Simulator.State.Positions.SequenceEqual(before) && s.Creature.Nodes.Count == 2 && s.Creature.Connections.Count == 1); });
Run("older files without features load empty", () => { var path = TempPath(); File.WriteAllText(path, "{\"Nodes\":[],\"Connections\":[],\"Chain\":{\"Spacing\":50,\"Stiffness\":1,\"Damping\":0.1},\"Body\":{\"BaseRadius\":24,\"RampPoints\":[{\"Position\":0,\"Value\":1},{\"Position\":1,\"Value\":0.4}]}}"); CreatureFileService.TryLoad(path, out var loaded, out _); File.Delete(path); Check(loaded!.Features.Count == 0); });
Run("appearance defaults are authored and play-safe", () => { var s = new EditorState(); Check(s.Creature.SkinColorArgb == 0xFF2E8B57 && s.Display.PlaySolidBody && !s.Display.PlayShowSkeleton && !s.Display.PlayShowMuscles && s.Display.PlayShowFeatures); });
Run("eye shape settings round trip", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); var eye = s.AddFeature(); eye.EyeWidth = 22; eye.EyeHeight = 11; eye.EyeTrackingStrength = 0.7f; var path = TempPath(); CreatureFileService.Save(path, s.Creature); CreatureFileService.TryLoad(path, out var loaded, out _); File.Delete(path); Check(loaded!.Features[0].EyeWidth == 22 && loaded.Features[0].EyeHeight == 11 && Math.Abs(loaded.Features[0].EyeTrackingStrength - 0.7f) < 0.001f); });
Run("skin color round trips and keeps opaque alpha", () => { var s = new EditorState(); s.SetSkinColor(0x123456); var path = TempPath(); CreatureFileService.Save(path, s.Creature); CreatureFileService.TryLoad(path, out var loaded, out _); File.Delete(path); Check(loaded!.SkinColorArgb == 0xFF123456); });
Run("old files receive skin defaults", () => { var path = TempPath(); File.WriteAllText(path, "{\"Nodes\":[],\"Connections\":[],\"Chain\":{\"Spacing\":50,\"Stiffness\":1,\"Damping\":0.1},\"Body\":{\"BaseRadius\":24,\"RampPoints\":[{\"Position\":0,\"Value\":1},{\"Position\":1,\"Value\":0.4}]}}"); CreatureFileService.TryLoad(path, out var loaded, out _); File.Delete(path); Check(loaded!.SkinColorArgb == 0xFF2E8B57); });
Run("bend constraint applies partial correction", () => { var creature = Definition(Vector2.Zero, new Vector2(50, 0), new Vector2(50 + MathF.Cos(100 * MathF.PI / 180) * 50, MathF.Sin(100 * MathF.PI / 180) * 50)); var play = new CreaturePlayState(); play.ResetFromDefinition(creature); var before = SignedBend(play.Positions); play.Step(creature, CreaturePlayState.FixedStep); var after = SignedBend(play.Positions); Check(Math.Abs(after) < Math.Abs(before) && Math.Abs(after) > play.MaxBendDegrees); });
Run("bend constraint preserves rest lengths", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.AddNextNode(); s.Simulator.Reset(s.Creature); s.Simulator.State.Positions[2] = s.Simulator.State.Positions[0]; s.Simulator.State.Step(s.Creature, CreaturePlayState.FixedStep); Check(s.Simulator.State.Positions.Zip(s.Simulator.State.Positions.Skip(1)).All(pair => Math.Abs(Vector2.Distance(pair.First, pair.Second) - s.Creature.ChainSettings.Spacing) < 0.01f)); });
Run("long constrained chains remain finite", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); for (var i = 0; i < 24; i++) s.AddNextNode(); s.SetMode(EditorMode.Play); s.SetPlayTarget(new Vector2(10000, -10000)); for (var i = 0; i < 600; i++) s.UpdateSimulation(CreaturePlayState.FixedStep); Check(s.Simulator.State.Positions.All(p => float.IsFinite(p.X) && float.IsFinite(p.Y)) && s.Simulator.State.Positions.Zip(s.Simulator.State.Positions.Skip(1)).All(pair => Math.Abs(Vector2.Distance(pair.First, pair.Second) - s.Creature.ChainSettings.Spacing) < 0.1f)); });
Run("moderate bend remains unchanged", () => { var creature = Definition(Vector2.Zero, new Vector2(50, 0), new Vector2(50 + MathF.Cos(40 * MathF.PI / 180) * 50, MathF.Sin(40 * MathF.PI / 180) * 50)); var play = new CreaturePlayState(); play.ResetFromDefinition(creature); var before = play.Positions.ToArray(); play.Step(creature, CreaturePlayState.FixedStep); Check(Vector2.Distance(before[2], play.Positions[2]) < 0.01f); });
Run("bend iterations converge without sign flip", () => { var creature = Definition(Vector2.Zero, new Vector2(50, 0), new Vector2(50 + MathF.Cos(130 * MathF.PI / 180) * 50, MathF.Sin(130 * MathF.PI / 180) * 50)); var play = new CreaturePlayState(); play.ResetFromDefinition(creature); var signs = new List<float>(); for (var i = 0; i < 30; i++) { play.Step(creature, CreaturePlayState.FixedStep); signs.Add(SignedBend(play.Positions)); } Check(signs.All(angle => angle > 0) && Math.Abs(signs[^1]) < Math.Abs(signs[0]) && Math.Abs(signs[^1]) <= play.MaxBendDegrees + 0.1f); });
Run("negative bend preserves negative direction", () => { var creature = Definition(Vector2.Zero, new Vector2(50, 0), new Vector2(50 + MathF.Cos(-110 * MathF.PI / 180) * 50, MathF.Sin(-110 * MathF.PI / 180) * 50)); var play = new CreaturePlayState(); play.ResetFromDefinition(creature); play.Step(creature, CreaturePlayState.FixedStep); Check(SignedBend(play.Positions) < 0); });
Run("straight chain remains straight", () => { var creature = Definition(Vector2.Zero, new Vector2(50, 0), new Vector2(100, 0), new Vector2(150, 0)); var play = new CreaturePlayState(); play.ResetFromDefinition(creature); play.Step(creature, CreaturePlayState.FixedStep); Check(BendAngles(play.Positions).All(angle => Math.Abs(angle) < 0.01f)); });
Run("smooth curve avoids alternating high curvature", () => { var creature = Definition(Vector2.Zero, new Vector2(50, 0), new Vector2(95, 15), new Vector2(132, 42), new Vector2(155, 78), new Vector2(165, 120)); var play = new CreaturePlayState(); play.ResetFromDefinition(creature); for (var i = 0; i < 8; i++) play.Step(creature, CreaturePlayState.FixedStep); var angles = BendAngles(play.Positions); Check(angles.All(angle => Math.Abs(angle) < play.MaxBendDegrees * MathF.PI / 180 + 0.2f) && angles.Zip(angles.Skip(1)).Count(pair => Math.Sign(pair.First) != Math.Sign(pair.Second) && Math.Abs(pair.First) > 0.25f && Math.Abs(pair.Second) > 0.25f) == 0); });
Run("construction circles match authored node data", () => { var positions = new[] { new Vector2(2, 3), new Vector2(42, 3), new Vector2(80, 18) }; var radii = new[] { 24f, 18f, 7f }; var circles = ConstructionCircleGeometry.Build(positions, radii); Check(circles.Length == 3 && circles.Select(c => c.Center).SequenceEqual(positions) && circles.Select(c => c.Radius).SequenceEqual(radii)); });
Run("construction circles follow ramp and base radius", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); var before = ConstructionCircleGeometry.Build(s.Creature.Nodes.Select(n => n.Position).ToArray(), s.Creature.Nodes.Select(n => n.Radius).ToArray()); s.SetBaseRadius(40); var after = ConstructionCircleGeometry.Build(s.Creature.Nodes.Select(n => n.Position).ToArray(), s.Creature.Nodes.Select(n => n.Radius).ToArray()); Check(after[0].Radius > before[0].Radius && after[1].Radius > before[1].Radius); });
Run("construction circles use simulated positions", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); s.SetMode(EditorMode.Play); s.Simulator.State.Positions[0] = new Vector2(12, 14); var circles = ConstructionCircleGeometry.Build(s.Simulator.State.Positions, s.Creature.Nodes.Select(n => n.Radius).ToArray()); Check(circles[0].Center == new Vector2(12, 14)); });
Run("construction circles do not mutate skin or simulation", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); var positions = s.Simulator.State.Positions.ToArray(); var radii = s.Creature.Nodes.Select(n => n.Radius).ToArray(); var skin = CreatureSkinGeometry.Build(positions, radii).Outline.ToArray(); _ = ConstructionCircleGeometry.Build(positions, radii); Check(s.Simulator.State.Positions.SequenceEqual(positions) && CreatureSkinGeometry.Build(positions, radii).Outline.SequenceEqual(skin)); });
Run("display toggles keep skeleton and muscles independent", () => { var s = new EditorState(); s.SetDisplay(false, true, true, true); Check(s.Display.CreateShowSkin && s.Display.CreateShowMuscles && !s.Display.CreateShowNodes); s.SetMode(EditorMode.Play); s.SetPlayDisplay(false, true, true, false, true); Check(!s.Display.PlayShowSkin && s.Display.PlaySolidBody && s.Display.PlayShowSkeleton && !s.Display.PlayShowMuscles); });
Run("wave and bend constraints remain stable together", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); for (var i = 0; i < 11; i++) s.AddNextNode(); s.SetWaveSettings(true, 18, 1.2f, 2.8f, 1); s.SetMode(EditorMode.Play); for (var i = 0; i < 180; i++) s.UpdateSimulation(CreaturePlayState.FixedStep); var angles = BendAngles(s.Simulator.State.Positions); Check(angles.All(angle => Math.Abs(angle) <= s.Simulator.State.MaxBendDegrees * MathF.PI / 180 + 0.2f) && s.Simulator.State.Positions.Zip(s.Simulator.State.Positions.Skip(1)).All(pair => Math.Abs(Vector2.Distance(pair.First, pair.Second) - s.Creature.ChainSettings.Spacing) < 0.1f)); });
Run("S curve preserves intentional bend signs", () => { var creature = Definition(Vector2.Zero, new Vector2(50, 0), new Vector2(92, 24), new Vector2(130, 0), new Vector2(172, -24), new Vector2(222, 0)); var play = new CreaturePlayState(); play.ResetFromDefinition(creature); for (var i = 0; i < 8; i++) play.Step(creature, CreaturePlayState.FixedStep); var angles = BendAngles(play.Positions); Check(angles.Any(angle => angle > 0.05f) && angles.Any(angle => angle < -0.05f) && angles.All(angle => Math.Abs(angle) < 75 * MathF.PI / 180 + 0.2f)); });
Run("undo create node restores empty authoring state", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.Undo(); Check(s.Creature.Nodes.Count == 0 && s.UndoCount == 0); });
Run("undo delete restores node chain and selection", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddNextNode(); var selected = s.SelectedNode; s.DeleteSelected(); s.Undo(); Check(s.Creature.Nodes.Count == 2 && s.SelectedNode?.Id == selected?.Id); });
Run("undo restores node property edit", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.SetSelectedNodeProperties(new Vector2(22, 18), 35); s.Undo(); Check(s.Creature.Nodes[0].Position == Vector2.Zero && s.Creature.Nodes[0].Rotation == 0); });
Run("undo restores ramp edit", () => { var s = new EditorState(); var point = s.AddRampPoint(0.5f, 1.5f)!; s.SetRampPoint(point, 0.6f, 0.8f); s.Undo(); var restored = s.Creature.BodySizeRamp.Points[1]; if (!(Math.Abs(restored.Value - 1.5f) < 0.001f && Math.Abs(restored.Position - 0.5f) < 0.001f)) throw new InvalidOperationException($"ramp {restored.Position} {restored.Value} points={s.Creature.BodySizeRamp.Points.Count}"); });
Run("undo restores feature add and delete", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); var feature = s.AddFeature(); s.DeleteSelectedFeature(); s.Undo(); Check(s.Creature.Features.Count == 1 && s.Creature.Features[0].Id == feature.Id); });
Run("grouped feature drag creates one undo state", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); s.AddFeature(); var before = s.UndoCount; s.BeginHistoryGroup(); s.SetSelectedFeatureLocalPosition(new Vector2(4, 4)); s.SetSelectedFeatureLocalPosition(new Vector2(8, 8)); s.EndHistoryGroup(); Check(s.UndoCount == before + 1); s.Undo(); Check(s.Creature.Features[0].LocalPosition == Vector2.Zero); });
Run("feature copy paste gives a new id and is undoable", () => { var s = new EditorState(); var head = s.CreateNode(Vector2.Zero); var feature = s.AddFeature(); feature.LocalPosition = new Vector2(12, 5); s.CopySelectedFeature(); Check(s.PasteFeature()); var pasted = s.SelectedFeature!; Check(pasted.Id != feature.Id && pasted.Type == feature.Type && pasted.ParentNodeId == head.Id && pasted.LocalPosition == new Vector2(20, 13)); s.Undo(); Check(s.Creature.Features.Count == 1); });
Run("fin copy paste preserves fin parameters", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); var fin = s.AddFeature(CreatureFeatureType.Fin); fin.FinSide = FinSide.Left; fin.FinLength = 58; fin.FinAngularDamping = 2.5f; s.CopySelectedFeature(); Check(s.PasteFeature()); var pasted = s.SelectedFeature!; Check(pasted.Id != fin.Id && pasted.Type == CreatureFeatureType.Fin && pasted.FinSide == FinSide.Left && pasted.FinLength == 58 && Math.Abs(pasted.FinAngularDamping - 2.5f) < 0.001f); });
Run("fin copy paste does not apply free-position offset", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); var fin = s.AddFeature(CreatureFeatureType.Fin); fin.LocalPosition = new Vector2(80, -25); fin.LocalRotation = 40; s.CopySelectedFeature(); Check(s.PasteFeature() && s.SelectedFeature!.LocalPosition == Vector2.Zero && s.SelectedFeature.LocalRotation == 0); });
Run("fin placement ignores legacy local translation and rotation", () => { var fin = new CreatureFeature { Type = CreatureFeatureType.Fin, FinSide = FinSide.Right, LocalPosition = new Vector2(90, 30), LocalRotation = 75, FinBaseAngle = 10 }; var first = FinGeometry.Build(fin, Vector2.Zero, Vector2.UnitX, 40, FinGeometry.RestAngle(fin, Vector2.UnitX)); fin.LocalPosition = Vector2.Zero; fin.LocalRotation = 0; var second = FinGeometry.Build(fin, Vector2.Zero, Vector2.UnitX, 40, FinGeometry.RestAngle(fin, Vector2.UnitX)); Check(first.Attachment == second.Attachment && Math.Abs(first.Tip.X - second.Tip.X) < 0.001f && Math.Abs(first.Tip.Y - second.Tip.Y) < 0.001f); });
Run("empty feature paste is safe", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); Check(!s.PasteFeature() && s.Creature.Features.Count == 0); });
Run("eyes use white orb radius and readable tracking defaults", () => { var eye = new CreatureFeature(); var orb = EyeGeometry.Build(eye, new FeatureWorldTransform(Vector2.Zero, 0, 1)); Check(orb.Radius > 0 && orb.Radius == eye.EyeSize && EyeGeometry.OrbColorArgb == 0xFFFFFFFF && Math.Abs(eye.EyeTrackingStrength - 0.5f) < 0.001f && eye.SupportsMirroring); });
Run("tongue geometry provides three skeleton bones", () => { var tongue = new CreatureFeature { Type = CreatureFeatureType.ForkedTongue }; var geometry = ForkedTongueGeometry.Build(tongue, new FeatureWorldTransform(Vector2.Zero, 0, 1), 5); Check(geometry.Start != geometry.Junction && geometry.UpperTip != geometry.Junction && geometry.LowerTip != geometry.Junction); });
Run("fin attaches at one quarter radius on the selected side", () => { var fin = new CreatureFeature { Type = CreatureFeatureType.Fin, FinSide = FinSide.Right }; var right = FinGeometry.Build(fin, Vector2.Zero, Vector2.UnitX, 20, MathF.PI / 2); fin.FinSide = FinSide.Left; var left = FinGeometry.Build(fin, Vector2.Zero, Vector2.UnitX, 20, -MathF.PI / 2); Check(Math.Abs(right.Attachment.Y - 5) < 0.001f && Math.Abs(left.Attachment.Y + 5) < 0.001f); });
Run("mirrored fin reflects side and keeps rounded outline", () => { var fin = new CreatureFeature { Type = CreatureFeatureType.Fin, FinSide = FinSide.Right, Mirrored = true }; var primary = FinGeometry.Build(fin, Vector2.Zero, Vector2.UnitX, 20, MathF.PI / 2, false); var mirror = FinGeometry.Build(fin, Vector2.Zero, Vector2.UnitX, 20, -MathF.PI / 2, true); Check(Math.Abs(primary.Attachment.Y - 5) < 0.001f && Math.Abs(mirror.Attachment.Y + 5) < 0.001f && primary.Outline.Length >= 15 && primary.Outline[0] == primary.Outline[^1]); });
Run("fin length and width change procedural geometry", () => { var fin = new CreatureFeature { Type = CreatureFeatureType.Fin }; var shortFin = FinGeometry.Build(fin, Vector2.Zero, Vector2.UnitX, 10, MathF.PI / 2); fin.FinLength = 60; fin.FinWidth = 30; var longFin = FinGeometry.Build(fin, Vector2.Zero, Vector2.UnitX, 10, MathF.PI / 2); Check(Vector2.Distance(longFin.Attachment, longFin.Tip) > Vector2.Distance(shortFin.Attachment, shortFin.Tip) && longFin.Outline.Max(p => p.X) != shortFin.Outline.Max(p => p.X)); });
Run("fin spring state lags body heading and resets", () => { var creature = Definition(Vector2.Zero, new Vector2(50, 0)); var fin = new CreatureFeature { Type = CreatureFeatureType.Fin, ParentNodeId = creature.Nodes[0].Id, FinAngularStiffness = 1, FinAngularDamping = 2 }; creature.Features.Add(fin); var play = new CreaturePlayState(); play.ResetFromDefinition(creature); var before = play.GetFinAngle(fin, creature); play.Positions[1] = new Vector2(0, 50); play.Step(creature, CreaturePlayState.FixedStep); var after = play.GetFinAngle(fin, creature); Check(float.IsFinite(after) && Math.Abs(after - before) < MathF.PI / 2 && float.IsFinite(play.GetFinAngularVelocity(fin))); play.ResetFromDefinition(creature); Check(Math.Abs(play.GetFinAngularVelocity(fin)) < 0.001f); });
Run("higher fin stiffness follows target more closely", () => { var lowCreature = Definition(Vector2.Zero, new Vector2(50, 0)); var highCreature = lowCreature.Clone(); var lowFin = new CreatureFeature { Type = CreatureFeatureType.Fin, ParentNodeId = lowCreature.Nodes[0].Id, FinAngularStiffness = 1, FinAngularDamping = 2 }; var highFin = new CreatureFeature { Type = CreatureFeatureType.Fin, ParentNodeId = highCreature.Nodes[0].Id, FinAngularStiffness = 30, FinAngularDamping = 2 }; lowCreature.Features.Add(lowFin); highCreature.Features.Add(highFin); var low = new CreaturePlayState(); var high = new CreaturePlayState(); low.ResetFromDefinition(lowCreature); high.ResetFromDefinition(highCreature); low.Positions[1] = high.Positions[1] = new Vector2(0, 50); low.Step(lowCreature, CreaturePlayState.FixedStep); high.Step(highCreature, CreaturePlayState.FixedStep); var targetLow = FinGeometry.RestAngle(lowFin, Vector2.UnitY); var targetHigh = FinGeometry.RestAngle(highFin, Vector2.UnitY); Check(Math.Abs(Normalize(targetHigh - high.GetFinAngle(highFin, highCreature))) < Math.Abs(Normalize(targetLow - low.GetFinAngle(lowFin, lowCreature)))); });
Run("fin authored data survives save load", () => { var s = new EditorState(); var head = s.CreateNode(Vector2.Zero); var fin = s.AddFeature(CreatureFeatureType.Fin); fin.ParentNodeId = head.Id; fin.FinSide = FinSide.Left; fin.FinLength = 62; fin.FinWidth = 24; fin.FinBaseAngle = -18; fin.FinAngularStiffness = 7; fin.FinAngularDamping = 3; var path = TempPath(); CreatureFileService.Save(path, s.Creature); CreatureFileService.TryLoad(path, out var loaded, out _); File.Delete(path); var restored = loaded!.Features[0]; Check(restored.Type == CreatureFeatureType.Fin && restored.FinSide == FinSide.Left && restored.FinLength == 62 && restored.FinBaseAngle == -18 && restored.FinAngularStiffness == 7); });
Run("fin color and mirrored flag survive save load", () => { var s = new EditorState(); s.CreateNode(Vector2.Zero); var fin = s.AddFeature(CreatureFeatureType.Fin); fin.Mirrored = true; s.SetFinColor(0xFF123456); var path = TempPath(); CreatureFileService.Save(path, s.Creature); CreatureFileService.TryLoad(path, out var loaded, out _); File.Delete(path); Check(loaded!.FinColorArgb == 0xFF123456 && loaded.Features[0].Mirrored && fin.SupportsMirroring); });
Run("bezier handles initialize and survive save load", () => { var s = new EditorState(); s.SetRampInterpolation(RampInterpolationMode.Bezier); var point = s.Creature.BodySizeRamp.Points[0]; Check(point.OutHandle.HasValue && !point.InHandle.HasValue); s.SetRampHandle(point, true, new Vector2(0.2f, 0.4f)); var path = TempPath(); CreatureFileService.Save(path, s.Creature); CreatureFileService.TryLoad(path, out var loaded, out _); File.Delete(path); Check(loaded!.BodySizeRamp.Points[0].OutHandle == new Vector2(0.2f, 0.4f)); });
Run("bezier handle edits preserve point position and group undo", () => { var s = new EditorState(); s.SetRampInterpolation(RampInterpolationMode.Bezier); var point = s.Creature.BodySizeRamp.Points[0]; var before = point.OutHandle; var position = point.Position; var undoBefore = s.UndoCount; s.BeginHistoryGroup(); s.SetRampHandle(point, true, new Vector2(0.15f, 0.2f)); s.SetRampHandle(point, true, new Vector2(0.2f, 0.3f)); s.EndHistoryGroup(); Check(point.Position == position && s.UndoCount == undoBefore + 1 && point.OutHandle != before); s.Undo(); var restored = s.Creature.BodySizeRamp.Points[0]; Check(restored.Position == position && restored.OutHandle == before); });
Run("linear and smooth ramp modes retain no interactive handle behavior", () => { var s = new EditorState(); Check(s.Creature.BodySizeRamp.Interpolation != RampInterpolationMode.Bezier && s.Creature.BodySizeRamp.Points.All(p => !p.InHandle.HasValue && !p.OutHandle.HasValue)); s.SetRampInterpolation(RampInterpolationMode.Smooth); Check(s.Creature.BodySizeRamp.Points.All(p => !p.InHandle.HasValue && !p.OutHandle.HasValue)); });
Run("fin angular state is not serialized", () => { var creature = Definition(Vector2.Zero, new Vector2(50, 0)); var fin = new CreatureFeature { Type = CreatureFeatureType.Fin, ParentNodeId = creature.Nodes[0].Id }; creature.Features.Add(fin); var play = new CreaturePlayState(); play.ResetFromDefinition(creature); play.Step(creature, CreaturePlayState.FixedStep); var path = TempPath(); CreatureFileService.Save(path, creature); CreatureFileService.TryLoad(path, out var loaded, out _); File.Delete(path); Check(loaded!.Features[0].Type == CreatureFeatureType.Fin); });
Console.WriteLine($"{passed} editor tests passed.");

void Run(string name, Action test) { test(); passed++; Console.WriteLine($"PASS {name}"); }
void Check(bool condition) { if (!condition) throw new InvalidOperationException("assertion failed"); }
string TempPath() => Path.Combine(Path.GetTempPath(), $"creature-test-{Guid.NewGuid():N}.creature.json");
CreatureDefinition Definition(params Vector2[] positions)
{
    var creature = new CreatureDefinition();
    foreach (var position in positions) creature.Nodes.Add(new CreatureNode { Position = position });
    for (var i = 1; i < creature.Nodes.Count; i++) creature.Connections.Add(new CreatureConnection { ParentNodeId = creature.Nodes[i - 1].Id, ChildNodeId = creature.Nodes[i].Id, RestLength = Vector2.Distance(positions[i - 1], positions[i]) });
    return creature;
}
float SignedBend(IReadOnlyList<Vector2> positions) => BendAngles(positions)[0] * 180 / MathF.PI;
float[] BendAngles(IReadOnlyList<Vector2> positions)
{
    var angles = new float[Math.Max(0, positions.Count - 2)];
    for (var i = 1; i < positions.Count - 1; i++)
    {
        var a = Vector2.Normalize(positions[i] - positions[i - 1]);
        var b = Vector2.Normalize(positions[i + 1] - positions[i]);
        angles[i - 1] = MathF.Atan2(a.X * b.Y - a.Y * b.X, Vector2.Dot(a, b));
    }
    return angles;
}
float Normalize(float angle)
{
    while (angle > MathF.PI) angle -= MathF.Tau;
    while (angle < -MathF.PI) angle += MathF.Tau;
    return angle;
}
